- blocks/tiles/tiles.js
This change stops using the admin api and uses the article index
Fix #56 
Test URLs:
- After: https://issue-56--petplace--hlxsites.hlx.page/
> fix: replace the usage of the admin api with the index for the site

- templates/article-page/article-page.js
Fix #70 
Test URLs:
- After: https://issue-70--petplace--hlxsites.hlx.page/
As requested by customer, a table of contents for an article should only be displayed if a metadata value is set in the article's document. The metadata name is `Has ToC`, and can be seen on the [cat drinking fountain article](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA63589C1-6D11-488F-8C55-B1DC6391B9E2%7D&file=cat-drinking-fountains.docx&action=default&mobileredirect=true).
Example page _with_ a toc: https://issue-70--petplace--hlxsites.hlx.page/article/cats/pet-care/cat-drinking-fountains
Example page _without_ a toc: https://issue-70--petplace--hlxsites.hlx.page/article/dogs/pet-care/dog-care/grooming-your-dog/th …
> feat: only show table of contents when flagged in metadata

- scripts/scripts.js
Fix #84 
Test URLs:
- After: https://issue-84-hero--petplace--hlxsites.hlx.page/
This change will use `createResponsiveImage` to make the hero image responsive. It's based on the number of images appearing before the first `h1` in the authored document. The logic is as follows:
* If there are 3 images before the header, the first will be used for mobile, the second for tablet, and the third for desktop.
* When there are 2 images before the header, the first will be used for both mobile and tablet, and the second for desktop.
* If there is only 1 image, it will be used for all screen sizes.
The change also incorporates `createOptimizedImage` to replace the hero images with a rendition optimized for the screen width.
This page has …
> feat: build responsive hero images

- templates/ask-author-page/ask-author-page.css
- templates/ask-author-page/ask-author-page.js
Fix #46
Test URLs:
- After: https://issue-46-white-arrow--petplace--hlxsites.hlx.page/
It turns out that changing the color of an `svg` with the css `color` property doesn't work when the `svg` is used as the `content` of a `::before` element. I tried playing around with setting a background and using `mask`, but ultimately it seemed simpler to me to just add a new `span` element for the arrow and avoid the fancy CSS. Let me know what you think.
This change applies to:
- https://issue-46-white-arrow--petplace--hlxsites.hlx.page/tags/ask-dr-debra-common-questions
> feat: change arrow color on Ask Now button to white

- scripts/scripts.js
- styles/styles.css
Fix #48 
Test URLs:
- After: https://issue-48--petplace--hlxsites.hlx.page/
This PR adds "skip to" buttons to the site. The buttons are hidden by default, but are revealed when they're focused. They're the first focusable elements on the page, so pressing the tab button will reveal them. Interacting with the buttons will focus the corresponding location in the page:
* "Skip to Content" will focus the `<main>` element.
* "Skip to Menu" will focus the first `li`'s `<a>` element in the page's primary navigation.
* "Skip to Footer" will focus the `<footer>` element.
All of the "Skip to" buttons are in a containing `<nav>` element, which is fixed, covers the entire content of the window, has a transparent background, and a `z-index` of -1. …
> feat: add a11y "skip to" links

- blocks/tiles/tiles.js
Test URLs:
- After: https://tiles-fallback--petplace--hlxsites.hlx.page/
> fix: tiles on homepage don't load if index isn't up-to-date

- scripts/scripts.js
Fix #203 #204 #205
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/birds/general/what-to-do-if-your-bird-flies-the-coop
- After: https://issue-203--petplace--hlxsites.hlx.live/article/birds/general/what-to-do-if-your-bird-flies-the-coop
The reason cause the navigation error is the unsuccess matching the article with its category name, while using slug instead can solve it.
After:
However, the searching algorithm is not very efficient, which may cause the delayed loading of the navigation bar. (I think it is fine, as it is at the bottom, but we do can improve it if needed. )
> fix: using slug to match instead of using name

- blocks/ad/ad.css
- blocks/ad/ad.js
- scripts/delayed.js
- scripts/scripts.js
Testing a hybrid approach where ads on desktop are loaded eagerly, and delayed on mobile to limit TBT there
Test URLs:
- After: https://ads-hybrid--petplace--hlxsites.hlx.page/
> fix: speed up ads loading on desktop

- blocks/cards/cards.js
- scripts/ffetch.js
- scripts/scripts.js
- templates/category-index/category-index.js
This PR fixes a bunch of issues that lead to the cards not being updated when the sub-category buttons are clicked.
1. The placeholders got removed in the mutation observer when we only wanted to remove the actual content divs instead
2. The `meterCalls` function didn't clear its state properly and couldn't be called a second time once done, so the soft navigation was never updating the content
3. The generator function from `ffetch` kept firing after the soft navigation, essentially adding nodes from the previous filter to the current view, so added an `interrupt` method to it
Fix #231 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/category/pet-care/
- After: https://issue-231--petplace--hlxsites.hlx.page/article/category/pet-care/
> fix: sub-categories softnav not loading new articles properly

- blocks/article-navigation/article-navigation.js
- blocks/pagination/pagination.js
- blocks/tiles/tiles.js
- templates/category-index/category-index.js
- templates/searchresults/searchresults.js
Older articles that were published years/months ago, will tend to be at the end of the ffetch pagination. Hence when we compute the next/prev article navigation links, and also when we search or list articles in an "old" category, it takes a long while to traverse the 10K articles via the default 255 batch size that ffetch has.
Seeing that a 2K batch size takes ~1.2s, we can use that instead by default and still have good enough performance on the 1st page, but then greatly speed up the traversal of the 10K pages if needed
Test URLs:
- After: https://opt-ffetch-chunks--petplace--hlxsites.hlx.page/
> fix: optimize ffetch traversal queries

- templates/puppy-diaries-index/puppy-diaries-index.css
- templates/puppy-diaries-index/puppy-diaries-index.js
Fix #195 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/puppy-diaries/
- After: https://issue-195--petplace--hlxsites.hlx.page/drafts/frisbey/puppy-diaries-index
Adds a new template for the puppy diaries index page, and flesh out mobile, tablet, and desktop views.
> add template for puppy diaries index page.

- templates/searchresults/searchresults.js
Test URLs:
- After: https://searchresults--petplace--hlxsites.hlx.page/
> fix: search results pagination according to upadated metercall

- blocks/popular-tags/popular-tags.js
- templates/category-index/category-index.js
- templates/tag-index/tag-index.css
- templates/tag-index/tag-index.js
This is essentially a copy/paste of the category index template just leveraging the tags json endpoint and stripping away the custom image and color logic for the hero.
Fix #258 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/tags/dr-debras-posts
- After:
- https://fix-tag-pages--petplace--hlxsites.hlx.live/tags/dr-debras-posts
- https://fix-tag-pages--petplace--hlxsites.hlx.live/tags/pet-tips-for-dogs
> feat: add tag index pages

- .github/pull_request_template.md
- blocks/ad/ad.js
- scripts/delayed.js
- scripts/scripts.js
Add the capability to disable the martech stack via a query parameter (`?martech=off`), and update PR template to leverage this new flag so it's easier to measure the impact of code changes on the site.
Test URLs:
- After:
- https://add-martech-flag--petplace--hlxsites.hlx.page/
- https://add-martech-flag--petplace--hlxsites.hlx.page/?martech=off
> feat: add capability to disable martech via query parameter

- blocks/popular-articles/popular-articles.js
This PR updates the popular posts block so that it falls back to the page's title if a `og:image:alt` metadata property isn't available.
Fix #272
Test URLs:
- After:
- https://issue-272--petplace--hlxsites.hlx.page/article/cats/diseases-conditions-of-cats/everything-you-need-to-know-about-cat-licking
- https://issue-272--petplace--hlxsites.hlx.page/article/cats/diseases-conditions-of-cats/everything-you-need-to-know-about-cat-licking?martech=off
> fix popular posts not appearing

- blocks/article-navigation/article-navigation.js
- templates/article-page/article-page.js
For articles with multi-categories, we use the first category ( color, path...) to fetch info.
Fix #281 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/reptiles/general/ball-python-care
- After:
- https://issue-281--petplace--hlxsites.hlx.page/article/reptiles/general/ball-python-care
This article has categories: general, small-pet-health. We use general as its category for fetching color and path.
> fix: Multi-category  leads to unsuccessfully fetch category information

- scripts/scripts.js
- templates/breed-index/breed-index.js
- templates/category-index/category-index.js
- templates/tag-index/tag-index.js
Introduce a new tablet helper and fix the positioning of the sidebars on index pages as they appear below the cards at the moment
Test URLs:
- After:
- https://fix-sidebars--petplace--hlxsites.hlx.page/
- https://fix-sidebars--petplace--hlxsites.hlx.page/?martech=off
> fix: position of sidebar toggles on mobile/tablet

- templates/article-page/article-page.css
- templates/article-page/article-page.js
The current hero block on article pages flickers out of visibility during the breadcrumb load. This was initiall done to hide some CLS, but we can have a cleaner alternative to this.
Test URLs:
- After:
- https://fix-hero-flicker--petplace--hlxsites.hlx.page/article/general/pet-health/national-immunization-awareness-month
- https://fix-hero-flicker--petplace--hlxsites.hlx.page/article/general/pet-health/national-immunization-awareness-month?martech=off
> fix: flicker of hero block on article pages

- styles/styles.css
- templates/article-page/article-page.css
- templates/article-page/article-page.js
Fixing minor CLS issue for content images as the height/width auto actually bypasses the hardcoded default sizes and hence creates CLS when they are loaded.
Test URLs:
- After:
- https://fix-article-cls--petplace--hlxsites.hlx.page/?martech=off
- https://fix-article-cls--petplace--hlxsites.hlx.page/article/general/pet-care/microchipping-protection-if-pets-get-lost?martech=off
- https://fix-article-cls--petplace--hlxsites.hlx.page/article/category/pet-care/?martech=off
> fix: cls on article pages

- 404.html
Wordpress used to have different paginated URLs, and also support short vanity URLs.
This PR tries to handles those redirects client-side as a fallback if the server-side doesn't have them configured.
Test URLs:
- After:
- https://fix-404s--petplace--hlxsites.hlx.page/article/birds/general/choosing-a-ringneck-parakeet/2/ (invalid pagination)
- https://fix-404s--petplace--hlxsites.hlx.page/chemical-burns-in-cats/ (short vanity)
- https://fix-404s--petplace--hlxsites.hlx.page/article/dogs/selecting-a-dog/choosing-a-breed/choosing-a-keeshond (moved article)
> feat: fixing redirects for known urls

- scripts/scripts.js
Added a new content fragment called "newsletter-footer", with the following content:
Assuming I did it correctly, the newsletter auto block will read that fragment, then create the newsletter signup form in the website's footer from the fragment.
Fix #257 
Test URLs:
- After:
- https://issue-257-fragment--petplace--hlxsites.hlx.page/
- https://issue-257-fragment--petplace--hlxsites.hlx.page/?martech=off
> feat: add content fragment for newsletter footer auto block.

- blocks/newsletter-signup/newsletter-signup.css
Per team feedback, improve the contrast of the text on the newsletter submit button when disabled.
Fix #257
Test URLs:
- After:
- https://issue-257-disabled--petplace--hlxsites.hlx.page/
- https://issue-257-disabled--petplace--hlxsites.hlx.page/?martech=off
> feat: improve contrast on newsletter submission button when disabled

- blocks/article-author/article-author.js
- blocks/article-navigation/article-navigation.js
- blocks/cards/cards.js
- blocks/embed/embed.css
- blocks/embed/embed.js
- blocks/pet-insurance-quote/pet-insurance-quote.js
- blocks/popular-articles/popular-articles.js
- blocks/tiles/tiles.js
- templates/article-page/article-page.js
Adding various semantic schemas for better SEO:
- https://schema.org/Article with its author on article pages, including for popular posts and article navigation
- https://schema.org/Article on the home page and category index pages
- https://schema.org/Person for authors index
- https://schema.org/VideoObject and https://schema.org/SocialMediaPosting for the various embeds
Fix #312 
Test URLs:
- After:
- https://add-schemas--petplace--hlxsites.hlx.live/article/cats/pet-care/caracals-as-pets
- https://add-schemas--petplace--hlxsites.hlx.live/
- https://add-schemas--petplace--hlxsites.hlx.live/article/category/pet-care/
- https://add-schemas--petplace--hlxsites.hlx.live/authors/
> feat: add semantic schemas

- templates/article-page/article-page.js
Adds support for specifying the `Type: FAQ` metadata on an article so it gets automatically decorated with the https://schema.org/FAQPage so it gets better indexing by Google (see: https://developers.google.com/search/docs/appearance/structured-data/faqpage).
Test URLs:
- After:
- https://faq-pages--petplace--hlxsites.hlx.live/article/dogs/pet-care/dog-faq-part-1
- https://faq-pages--petplace--hlxsites.hlx.live/article/dogs/pet-care/dog-faq-part-2
- https://faq-pages--petplace--hlxsites.hlx.live/article/dogs/just-for-fun/can-the-avian-flu-bird-flu-infect-dogs
> feat: add support for annotating article pages as FAQ

- blocks/newsletter-signup/newsletter-signup.js
We've been seeing 400 responses from iterable, but there is no detail. Logging the response body as well as the status code whenever there are failures.
Test URLs:
- After:
- https://error-detail--petplace--hlxsites.hlx.page/
- https://error-detail--petplace--hlxsites.hlx.page/?martech=off
> feat: capture additional detail from iterable errors.

- blocks/ad/ad.js
On mobile, sometimes the ads flow outside of the viewport and are not properly constrained to the visible area of the page.
We fix this by:
1. checking against the available `width` of the parent
2. deferring the size check to after the block renders (otherwise `width` would just be `0`)
Test URLs:
- After:
- https://fix-ads-mobile--petplace--hlxsites.hlx.page/
- https://fix-ads-mobile--petplace--hlxsites.hlx.page/?martech=off
> fix: ads rendering on mobile

- blocks/form/form.js
- blocks/newsletter-signup/newsletter-signup.js
Create forms using `name` attribute instead of `id`. Ensure that newsletter form values are pulled from the block instead of the document.
Test URLs:
- After:
- https://newsletter-popup-fix--petplace--hlxsites.hlx.page/
- https://newsletter-popup-fix--petplace--hlxsites.hlx.page/?martech=off
> fix: send data when submitting newsletter from popup

- scripts/scripts.js
- scripts/third-party.js
Following https://adobe-dx-support.slack.com/archives/C04P5DFPDK9/p1695225389498879, we are moving the tag instrumentation from the webworker (partytown) directly in the main thread to avoid the CORS issues we are seeing.
Test URLs:
- After:
- https://gtm-tag-ads--petplace--hlxsites.hlx.live/
> feat: add GTM tag for ads tracking

- blocks/article-navigation/article-navigation.js
- blocks/popular-articles/popular-articles.js
- blocks/tiles/tiles.js
Removes the ItemList and Article schemas on some of the blocks since those are making it harder for Google to properly index the content.
Test URLs:
- After:
- https://simplify-schemas--petplace--hlxsites.hlx.page/
- https://simplify-schemas--petplace--hlxsites.hlx.page/?martech=off
> fix: simplify semantic schemas for better SEO

- scripts/scripts.js
- templates/searchresults/searchresults.js
The content for the 404 page is already properly localized through #371, but the meta tags still need to be adjusted:
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/invalid
- After:
- https://localized-404--petplace--hlxsites.hlx.live/invalid
- https://localized-404--petplace--hlxsites.hlx.live/invalid?martech=off
- https://localized-404--petplace--hlxsites.hlx.page/en-gb/invalid
- https://localized-404--petplace--hlxsites.hlx.page/en-gb/invalid?martech=off
> feat: properly localize the 404 page including meta tags

- helix-query.yaml
- helix-sitemap.yaml
- sitemap-index.xml
Adds properly localized sitemaps:
- add a sitemap index listing all regional ones
- add a new helix query definition for the UK sitemap
- add a new helix sitemap definition for the UK sitemap
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/sitemap.xml
- After:
- https://localized-sitemap--petplace--hlxsites.hlx.live/sitemap-index.xml
- https://localized-sitemap--petplace--hlxsites.hlx.live/sitemap.xml
- https://localized-sitemap--petplace--hlxsites.hlx.live/sitemap-en-gb.xml
> feat: properly localize the sitemaps

- helix-query.yaml
Adds a new index for the UK articles.
Test URLs:
- After:
- https://localized-articles--petplace--hlxsites.hlx.live/en-gb/article/query-index.json
- https://localized-articles--petplace--hlxsites.hlx.live/en-gb/article/query-index.json?martech=off
> feat: add localized article index

- scripts/adsense.js
- scripts/utils/helpers.js
- styles/styles.css
- templates/article-page/article-page.css
- templates/article-page/article-page.js
- sending article side to adsense script
- removed comments for helper file
- added condition to create div for side ad
- made the skyscraper sticky on scroll
- removed old setup for ads from blocks
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-88
Test URLs:
- After:
- https://feat-refactor-article-side-ads--petplace--hlxsites.hlx.live/
- https://feat-refactor-article-side-ads--petplace--hlxsites.hlx.live/?martech=off
Screenshots:
full article view
view on desktop
sticky while scrolling
> feat: refactor for ads on article side section

- scripts/adsense.js
- scripts/utils/helpers.js
- templates/breed-index/breed-index.js
- templates/breed-page/breed-page.css
- templates/breed-page/breed-page.js
- adsense setup for breeds pages (index/single)
- css modifications to allow for proper ads display
- modification to common func for different pages
- displaying breed slightly differently than others
- conditions for breed ads locations (top/middle/etc)
- helper function to better handle middle ad location
- checking adsense func if it's a page with middle ads
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-130
Test URLs:
- After:
- https://feat-breed-guide-ads--petplace--hlxsites.hlx.live/
- https://feat-breed-guide-ads--petplace--hlxsites.hlx.live/?martech=off
Screenshot Samples:
-  Single Breed Desktop (top/bottom)
-  Single Breed Mobile (middle/anchor)
- Breed Index Desktop (top/bottom)
- Breed Index …
> feat: ads for breed guide and single breed pages

- blocks/header/header.css
Fixes for search input and collapsible elements styles on safari
Test URLs:
http://localhost:3000/
> [PPAD-291] [QA] - Main Navigation - The "Pet Articles" tab in the menu does not look set in Safari browser

- blocks/adopt-search/adopt-search.css
- blocks/header/header.css
- templates/adopt/adopt.css
[PPAD-169](https://pethealthinc.atlassian.net/browse/PPAD-169) [QA] - Landing Page - Tablet View - The design does not match Figma
[PPAD-170](https://pethealthinc.atlassian.net/browse/PPAD-170) [QA] - Landing Page - Mobile View - The design does not match Figma
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/pet-adoption/
- After:
http://localhost:3000/pet-adoption/
Questions: 
1. "The size of the cards should be rendered and match the design in tablet view, Width: 250 px, Height: 385 px"
I fixed the width, but want to confirm first if we should fix the height of the card?
2." PetPlace: More than Just An Adoption Site, title, font size: 49.5 px Description, Font Size: 24 px, Font Type: Inter"
Do we have this font family Inter? It seems to be a bug on Figma.
> [PPAD-169] [PPAD-170] Landing Page - Mobile and Tablet views

- blocks/header/header.js
- templates/gen-ai/gen-ai.js
Move the global reference in the header to the dedicated template to reduce performance impact.
Also remove unused dependencies.
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/discovery
- After:
- https://fix-marked-loading--petplace--hlxsites.hlx.live/discovery
- https://fix-marked-loading--petplace--hlxsites.hlx.live/discovery?martech=off
> fix: load marked only when needed

- scripts/scripts.js
It looks like after merging #469 the analytics tracking stopped properly working. This seems to be caused by a race condition in the way the martech is loaded and that doesn't recognize the pushed events on the data layer.
Switching over the the explicit `gtag(…)` approach seems to fix it.
Test URLs:
- After:
- https://fix-analytics--petplace--hlxsites.hlx.live/
> fix: analytics tracking stopped working post martech experiment

- blocks/pet-survey/pet-survey.js
Fix #PPAD-411:
Test URLs:
- After:
> PPAD-411: track change events also in renderAsNonUser survey summary

- styles/fonts.css
Missing font faces for bold font weights is causing Safari to overly stretch the font.
Fix: [PM-335](https://pethealthinc.atlassian.net/browse/PM-335)
Test URLs:
- After:
- https://bugfix-safari-font-issue--petplace--hlxsites.hlx.page/
- https://bugfix-safari-font-issue--petplace--hlxsites.hlx.page/?martech=off
> bugfix(PM-335): Add missing font face for Libre Franklin

- icons/chevron-large.svg
- scripts/scripts.js
- styles/styles.css
- templates/author-page/author-page.js
- templates/insurance-page/insurance-page.css
- templates/insurance-page/insurance-page.js
Adjust createBreadcrumb to support new options
Fix: [PM-331](https://pethealthinc.atlassian.net/browse/PM-331)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california
- After:
- https://feat-insurance-page-breadcrumb--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california
- https://feat-insurance-page-breadcrumb--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california?martech=off
> feat(PM-331): Add breadcrumbs to Insurance Pages

- blocks/pet-survey/pet-survey.css
Fix #PPAD-408
Test URLs:
http://localhost:3000/pet-adoption/survey?animalId=30779404&clientId=PP2528&animalType=dog
> [PPAD-408] Confirmation screen text trimmed on mobile

- scripts/scripts.js
Using "audiences" checkpoint to send language and region data and expand the default region mapping list.
Fix #
Test URLs:
- After:
- https://22691-update-default-region-map--petplace--hlxsites.hlx.live/
- https://22691-update-default-region-map--petplace--hlxsites.hlx.live/?martech=off
> [SITES-22691] Use "audiences" checkpoint to track language and region in RUM data

- templates/category-index/category-index.js
Error is preventing publishing authoring changes
Fix: [PM-277](https://pethealthinc.atlassian.net/browse/PM-277)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/category/default
- After:
- https://hotfix-category-tags-default--petplace--hlxsites.hlx.page/article/category/default
-   - https://hotfix-category-tags-default--petplace--hlxsites.hlx.page/article/category/default?martech=off
> hotfix: Prevent 404 error on default page for category and tags

- blocks/pet-survey/pet-survey.js
Fix [Duplicate survey answers being stored](https://phits.visualstudio.com/PetPlace/_workitems/edit/81181)
The `surveyAnswers` state was being updated with duplicated answers, so I created an utility to remove the old answer before pushing a new one, which should fix that problem.
Test URLs:
- After:
- https://81181-fix-duplicated-survey-answers--petplace--hlxsites.hlx.live/
- https://81181-fix-duplicated-survey-answers--petplace--hlxsites.hlx.live/?martech=off
> fix: Removed duplicated survey answers

- templates/gen-ai/gen-ai.css
**Issue:** The hero image gets cropped from top when you go to wider screens (or zoom out). Refer to ticket for expected image visual presentation.
Fix: [PM-224](https://pethealthinc.atlassian.net/browse/PM-224)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/discovery
- After:
https://bugfix-genai-hero-image-crop--petplace--hlxsites.hlx.page/discovery
https://bugfix-genai-hero-image-crop--petplace--hlxsites.hlx.page/discovery/?martech=off
> fix: GenAI - Hero Image Crop

- blocks/related-reading/related-reading.js
- templates/category-index/category-index.js
Introducing individual indexes (i.e. filtered sheets in the `/articles/query-index.js` workbook) for each article category and tag to speed up the page rendering for category index (pagination) and article pages (related readings).
Test URLs:
- After:
- https://category-indexes--petplace--hlxsites.hlx.page/article/category/pet-care/dog-care
- https://category-indexes--petplace--hlxsites.hlx.page/article/category/pet-care/dog-care?martech=off
- https://category-indexes--petplace--hlxsites.hlx.page/article/general/pet-care/dog-care/dog-adoption/the-reasons-to-adopt-a-pet-instead-of-buying-one
- https://category-indexes--petplace--hlxsites.hlx.page/article/general/pet-care/dog-care/dog-adoption/the-reasons-to-adopt-a-pet-instead-of-buying-o …
> chore(perf): improve page performance by creating category and tag indexes

- blocks/cards/cards.css
- scripts/scripts.js
- templates/breed-index/breed-index.css
- templates/breed-index/breed-index.js
The current breed index page has seen a drop in performance recently. We'll focus on fixing the CLS, as the TBT is mostly caused by the martech stack.
| Mobile | Desktop |
|-|-|
| <img width="963" alt="Screenshot 2024-08-02 at 15 10 28" src="https://github.com/user-attachments/assets/c3093e93-0e97-4833-aaa6-4ea775703aa3"> | <img width="965" alt="Screenshot 2024-08-02 at 15 10 35" src="https://github.com/user-attachments/assets/c3ab267d-4fe5-4e7d-b162-d8de331c7918"> |
As we can see in the performance audit, we have mainly 3 layout shifts:
With respectively:
This hints at:
1. The filters are shifted by something injected before it, after it rendered (i.e. the hero block)
2. The filters, images, slide cards, etc. are all shifted after rendering, which is due to the hero block being generated …
> chore(perf): fix the CLS on the breed index pages

- blocks/pagination/pagination.js
**Issue:** When on the Breed Category [page](https://www.petplace.com/article/breed/?page=12) -> it shows 12 pages in the pagination. However users are able to proceed past that, to the 13th page, which is shown as empty.
Fix: [PM-460](https://pethealthinc.atlassian.net/browse/PM-460)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/breed/?page=12
- After:
- https://bugfix-breed-category-pagination--petplace--hlxsites.hlx.page/article/breed/?page=12
- https://bugfix-breed-category-pagination--petplace--hlxsites.hlx.page/article/breed/?page=12/?martech=off
> fix: Breed Category - Pagination

- templates/category-index/category-index.js
- templates/tag-index/tag-index.js
Currently, categories and tags index pages will return a soft 404 when the specified category/tag does not exist.
This flags the page as a soft 404 in the Google Search Index. The recommendation is to change this so we return a proper 404 page (i.e. via JS redirection).
Test URLs:
- After:
- https://fix-soft-redirects--petplace--hlxsites.hlx.live/article/category/some-invalid-category
- https://fix-soft-redirects--petplace--hlxsites.hlx.live/article/category/some-invalid-category?martech=off
> fix: soft redirects should point to real 404 page so Google properly marks it in GSC

- templates/category-index/category-index.js
Referral traffic still reaches the site using old paginated category URLs with the form `…/page/3/`, which breaks our category detection on the category index pages.
The PR fixes this so we serve the main category page instead. Actual page index is consciously ignored, as the canonical will properly be set to the 1st page, and thus googe search won't index the duplicated content.
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/category/pet-health/small-pet-health/fish-small-pet-health/page/3/
- After:
- https://<branch>--petplace--hlxsites.hlx.live/article/category/pet-health/small-pet-health/fish-small-pet-health/page/3/
- https://<branch>--petplace--hlxsites.hlx.live/article/category/pet-health/small-pet-health/fish-small-pet-health/page/3/?martech=off
> feat: properly resolve legacy category instead of 404

- blocks/account/account-favorites.js
We're seeing rage clicks on the `.account #favorites` selector, so adding more detailed information to RUM to see if the rage clicks are happening on the image or info or remove favorite.
Test URLs:
- After:
- https://account-favorites-rum--petplace--hlxsites.hlx.page/
> fix: adding data rum source for account favorites to know where the rage clicks happening

- scripts/adsense.js
- scripts/lib-franklin.js
- scripts/scripts.js
- scripts/third-party.js
After enabling speculative prerendering to speed up the page rendering during navigation, we saw an increase in various 3rd-party metrics being tracked (page views, etc.). This PRs properly wraps those instrumentation behind prerender compatible events so they only trigger if the page is actually activated (i.e. navigated to) by the end user
Test URLs:
- After:
- https://fix-prerender--petplace--hlxsites.hlx.live/
- https://fix-prerender--petplace--hlxsites.hlx.live/?martech=off
> fix: prerender aware RUM & analytics tracking and ads improvessions

- react-client/src/routes/my-pets/petId/useRenewMembershipViewModel.ts
This PR solves the issue:
- https://phits.visualstudio.com/PetPlace/_workitems/edit/84734
before
after
Test URLs:
- Before: https://dev--petplace--hlxsites.hlx.page/
- After:
- https://fix-84734--petplace--hlxsites.hlx.live/
- https://fix-84734--petplace--hlxsites.hlx.live/?martech=off
> fix: 84734 unable to access pet profile
