hlxsites/petplace

blocks/article-author/article-author.js, blocks/article-navigation/article-navigation.js, blocks/navigation/navigation.js, blocks/paws-up-count/paws-up-count.js, blocks/paws-up/paws-up.js, blocks/popular-articles/popular-articles.js, blocks/social-links/social-links.js, blocks/table-of-contents/table-of-contents.css, blocks/table-of-contents/table-of-contents.js, scripts/scripts.js, templates/article-page/article-page.css, templates/article-page/article-page.js, templates/breed-page/breed-page.css, templates/breed-page/breed-page.js, templates/categories-page/categories-page.js
Fix #8
Test URLs:
- After: https://issue-8-breed-template--petplace--hlxsites.hlx.page/
This PR has a few changes:
* Add placeholders in all unfinished blocks used by current templates.
* Move table of contents creation from main scripts.js to article template.
* Add ability for templates to control the hero block creation (the breeds template has a unique hero layout)
* Finish mobile layout for breeds template.
=> Flesh out breed template

blocks/article-author/article-author.css, blocks/article-author/article-author.js, blocks/article-navigation/article-navigation.css, blocks/article-navigation/article-navigation.js, blocks/columns/columns.css, blocks/footer/footer.css, blocks/navigation/navigation.js, blocks/paws-up-count/paws-up-count.css, blocks/paws-up-count/paws-up-count.js, blocks/paws-up/paws-up.css, blocks/paws-up/paws-up.js, blocks/popular-articles/popular-articles.js, blocks/slideshow/slideshow.css, blocks/social-links/social-links.js, blocks/table-of-contents/table-of-contents.css, blocks/table-of-contents/table-of-contents.js, scripts/scripts.js, styles/styles.css, templates/article-page/article-page.css, templates/article-page/article-page.js, templates/breed-page/breed-page.css, templates/breed-page/breed-page.js, templates/categories-page/categories-page.js, templates/home-page/home-page.js
Fix #29 
Test URLs:
- After: https://<branch>--petplace--hlxsites.hlx.page/
=> merge latest

blocks/columns/columns.css, blocks/tiles/tiles.js, scripts/aria/aria-dialog.js, scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://dynamic-categories--petplace--hlxsites.hlx.page/
=> feat: add support for dynamically resolving categories

blocks/attributes/attributes.js, blocks/general-attributes/general-attributes.css, blocks/general-attributes/general-attributes.js, templates/breed-page/breed-page.css
Replace the div structure with a `dl/dt/dd` for better semantics and switch to a grid for an easier layout.
Also address minor fixes to the attributes block at the same time.
Fix #87
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/breed/pembroke-welsh-corgi
- After: https://issue-87--petplace--hlxsites.hlx.page/article/breed/pembroke-welsh-corgi
=> feat: improve semantics of general attributes block

blocks/tiles/tiles.css
Fix #98 
Test URLs:
- After: https://issue-98--petplace--hlxsites.hlx.page/
=> issue-98: adding very small mobile styles

blocks/breadcrumb/breadcrumb.css, blocks/breadcrumb/breadcrumb.js, scripts/scripts.js, templates/article-page/article-page.css, templates/article-page/article-page.js, templates/author-page/author-page.css, templates/author-page/author-page.js, templates/breed-index/breed-index.css, templates/breed-index/breed-index.js, templates/category-index/category-index.css, templates/category-index/category-index.js
Test URLs:
- After: https://issue-29--petplace--hlxsites.hlx.page/
=> fetch latest

blocks/tiles/tiles.js, helix-query.yaml
Fix #112 
Test URLs:
- After: https://issue-112--petplace--hlxsites.hlx.page/
=> issue -112 adding alt text to tile images

blocks/tiles/tiles.js
Test URLs:
- After: https://update-homepage--petplace--hlxsites.hlx.page/
=> feat: update homepage

blocks/blade/blade.js, blocks/footer/footer.css, blocks/pagination/pagination.css, blocks/pagination/pagination.js, blocks/slide-cards/slide-cards.css, blocks/slide-cards/slide-cards.js, blocks/slideshow/slideshow.js, blocks/social-links/social-links.js, blocks/social-share/social-share.js, blocks/tiles/tiles.css, blocks/tiles/tiles.js, scripts/scripts.js
Test URLs:
- After: https://perfs--petplace--hlxsites.hlx.page/
=> fix: various score improvements to the LHS

.eslintrc.js, blocks/popular-articles/popular-articles.css, blocks/popular-articles/popular-articles.js, templates/article-page/article-page.css
Fetching popular posts from a document... fallback to home page slideshow.
Fix #43 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/dogs/pet-health/hip-dysplasia-in-dogs
- After: https://issue-43--petplace--hlxsites.hlx.page/article/dogs/pet-health/hip-dysplasia-in-dogs
=> Issue 43 - Popular Posts Block

tools/sidekick/config.json
Need to get the sidkick plugin merged to main first to work with the share point docs
Fix #95 
Test URLs:
- After: https://issue-95--petplace--hlxsites.hlx.page/
=> sidekick plugin

scripts/scripts.js, templates/article-page/article-page.js
Breadcrumbs were showing incorrect information.
Compare urls for example.  Previoulsy we were just breaking down the url, now we look at category information and go up the parent chain.
Fix #143 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/dogs/pet-health/hip-dysplasia-in-dogs
- After: https://issue-143--petplace--hlxsites.hlx.page/article/dogs/pet-health/hip-dysplasia-in-dogs
=> correcting the breadcrum display

blocks/breadcrumb/breadcrumb.css, scripts/scripts.js
Updating markup and visuals for breadcrumbs
Fix #104 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/cats/pet-care/cat-care/senior-cat-care/heres-older-cat-wants-attention-often
- After: https://issue-104--petplace--hlxsites.hlx.page/article/cats/pet-care/cat-care/senior-cat-care/heres-older-cat-wants-attention-often
=> updating the breadcrumbs markup to be WCAG compliant

scripts/lib-franklin.js, tools/sidekick/config.json, tools/sidekick/library.html
Do not merge until https://github.com/adobe/helix-website/pull/275 is merged
This PR migrates the petplace site to the new full screen version of the sidekick library.
Test URLs:
Before: https://main--petplace--hlxsites.hlx.page/
After: https://sidekick-library-migration--petplace--hlxsites.hlx.page/
=> fix: migration to new sidekick library

scripts/scripts.js, templates/category-index/category-index.js
Test URLs:
- After: https://404-redirect--petplace--hlxsites.hlx.page/
=> feat: redirect to 404 on missing category

blocks/cards/cards.js, blocks/header/header.js, scripts/aria/aria-treeview.js, scripts/lib-franklin.js, scripts/scripts.js, styles/lazy-styles.css, templates/category-index/category-index.js
Test URLs:
- After:
- https://fix-cls--petplace--hlxsites.hlx.page/
- https://fix-cls--petplace--hlxsites.hlx.page/article/general/just-for-fun/pets-in-famous-art-a-brief-history
- https://fix-cls--petplace--hlxsites.hlx.page/article/category/pet-care/
=> fix: cls and tbt in sidenav

blocks/accordion/accordion.css, blocks/article-author/article-author.css, blocks/attributes/attributes.css, blocks/header/header.css, blocks/popular-tags/popular-tags.css, blocks/slideshow/slideshow.css, blocks/sub-categories/sub-categories.css, blocks/tiles/tiles.css, styles/lazy-styles.css, styles/styles.css
Fix #153
Test URLs:
- After: https://issue-153--petplace--hlxsites.hlx.page/
=> fix: add high-contrast styles for links and buttons

head.html, scripts/delayed.js, scripts/scripts.js
Fix #138
Fix #30 
Test URLs:
- After:
- https://issue-138--petplace--hlxsites.hlx.page/
- https://issue-138--petplace--hlxsites.hlx.page/article/cats/pet-care/how-to-raise-a-happy-friendly-kitten-or-cat
- https://issue-138--petplace--hlxsites.hlx.page/article/breed/bernese-mountain-dogs
=> feat: instrument the martech stack

scripts/scripts.js, templates/article-page/article-page.css
Fix #158 
Test URLs:
- After:
- https://issue-158--petplace--hlxsites.hlx.page/article/cats/pet-care/how-to-raise-a-happy-friendly-kitten-or-cat
- https://issue-158--petplace--hlxsites.hlx.page/article/category/pet-care/
=> fix: cls due to breadcrumb

blocks/cards/cards.css, blocks/cards/cards.js, scripts/scripts.js, templates/category-index/category-index.js
Fix #169
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/category/pet-care/
- After: https://issue-169--petplace--hlxsites.hlx.page/article/category/pet-care/
=> feat: add skeleton loading animation to cards loading logic

.eslintignore, .stylelintignore, blocks/blade/blade.css, scripts/lite-yt-embed/lite-yt-embed.css, scripts/lite-yt-embed/lite-yt-embed.js, scripts/scripts.js, styles/styles.css
Fix #174 
Test URLs:
- After: https://issue-174--petplace--hlxsites.hlx.page/about-us
=> feat: implement about-us page

blocks/form/form.css, blocks/form/form.js, blocks/hero/hero.css, scripts/lib-franklin.js, scripts/scripts.js, styles/styles.css
Fix #176
Test URLs:
- After: https://issue-176--petplace--hlxsites.hlx.page/advertise-with-us
=> feat: implement contact form

scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://link-opening--petplace--hlxsites.hlx.page/
=> feat: standardize link navigation

blocks/search/search.css, scripts/scripts.js, templates/searchresults/searchresults.css, templates/searchresults/searchresults.js
Fix #181 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/search
- After: https://issue-181--petplace--hlxsites.hlx.page/search
=> css and logic changes for search header and search input

blocks/embed/embed.css, blocks/embed/embed.js, scripts/scripts.js, styles/styles.css
Fix #123 
Fix #137
Fix #149  
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/cats/pet-care/neko-cat-cafe
- Tiktok: https://issue-123--petplace--hlxsites.hlx.page/article/cats/pet-care/neko-cat-cafe
- Instagram: https://issue-123--petplace--hlxsites.hlx.page/article/general/just-for-fun/pets-as-easter-bunnies
- Youtube: https://issue-123--petplace--hlxsites.hlx.page/about-us
=> Issue 123 - Instagram and Tiktok embed

icons/down-chevron.svg, scripts/scripts.js, templates/searchresults/searchresults.css, templates/searchresults/searchresults.js
Fix #49 
Test URLs:
- After: https://issue-49--petplace--hlxsites.hlx.page/search?query=dogs
=> issue 49 sort button implementation

404.html
Fix #218 
Test URLs:
- After: https://redirect-404--petplace--hlxsites.hlx.page/
=> Redirect 404

blocks/cards/cards.css
Fix #216 
Test URLs:
- Before:https://main--petplace--hlxsites.hlx.live/article/category/pet-care/
- After: https://issue-216--petplace--hlxsites.hlx.live/article/category/pet-care/
=> fix:blog card category inset

blocks/breadcrumb/breadcrumb.css, scripts/scripts.js, templates/article-page/article-page.css, templates/author-page/author-page.css, templates/author-page/author-page.js
Fix #208 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/authors/dr-debra-primovic-dvm
- After: https://issue-208--petplace--hlxsites.hlx.live/authors/dr-debra-primovic-dvm
=> Fix: Undefined value in breadcurmb in authors page

templates/article-page/article-page.css
Fix #211 
Test URLs:
- Before:https://main--petplace--hlxsites.hlx.live/article/general/pet-care/4th-of-july-food-safety-for-pets
- After: https://issue-211--petplace--hlxsites.hlx.live/article/general/pet-care/4th-of-july-food-safety-for-pets
=> style:add margin before the popular posts on the article page

templates/article-page/article-page.css
Fix #210 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/general/pet-care/4th-of-july-food-safety-for-pets
- After: https://issue-210--petplace--hlxsites.hlx.live/article/general/pet-care/4th-of-july-food-safety-for-pets
=> style: Adjust h3 style in article page to align with their web

blocks/tiles/tiles.js
Test URLs:
- After: https://<branch>--petplace--hlxsites.hlx.page/
=> fix: tiles image size

blocks/article-author/article-author.js
Fix #191 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/general/pet-care/how-do-pet-microchips-work
- After: https://issue-191--petplace--hlxsites.hlx.live/article/general/pet-care/how-do-pet-microchips-work
=> fix: article author should link to author page (if it exists)

templates/article-page/article-page.js
Fix #213 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/general/news/new-york-banning-retail-pet-sales-puppy-mills
- After: https://issue-213--hlxsites.hlx.live/article/general/news/new-york-banning-retail-pet-sales-puppy-mills
=> fix:Position of ToC block relative to disclosure block

scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://optimize-skeleton-animations--petplace--hlxsites.hlx.page/
=> fix: optimize skeleton animations

blocks/cards/cards.css, blocks/tiles/tiles.css
Before:
After:
Fix #242 
Test URLs:
- After: https://issue-242--petplace--hlxsites.hlx.page/
=> fix:title padding style and cards border issue

templates/searchresults/searchresults.js
Fix #240 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/search?query=testtesttest
- After: https://issue-240--petplace--hlxsites.hlx.page/search?query=testtesttest
=> fix: remove skeleton in search page when no results found

scripts/delayed.js, scripts/scripts.js, templates/article-page/article-page.js
Test URLs:
- After:
- https://fix-ads--petplace--hlxsites.hlx.live/
- https://fix-ads--petplace--hlxsites.hlx.live/article/category/pet-care/
- https://fix-ads--petplace--hlxsites.hlx.live/article/general/pet-care/roborock-s7-max-ultra-for-high-traffic-homes-with-pets
=> refactor: do not load gpt.js when there are no ads

templates/category-index/category-index.js
Fix #202 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/category/pet-health/
- After: https://issue-202--petplace--hlxsites.hlx.page/article/category/pet-health/
Displays the message `No Articles Found` as an `h2` on the category index page if there are no articles in the category.
=> display a message when there are no articles in a category

scripts/scripts.js
The current implementation of the metering function isn't resolving at the right time and leaves unfulfilled promises dangling. This essentially means that we never fully resolve the metering function in the callers when called multiple times, and this ultimately leaves the skeleton elements in place.
Test URLs:
- After: https://fix-metering--petplace--hlxsites.hlx.page/
=> Fix metering

scripts/scripts.js, templates/category-index/category-index.js
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/category/pet-care/cat-care/cat-exercises-play/
- After:
- https://fix-index-pages--petplace--hlxsites.hlx.page/article/category/pet-care/cat-care/cat-exercises-play/
- https://fix-index-pages--petplace--hlxsites.hlx.live/article/category/pet-care/cat-care/cat-exercises-play/
=> fix: skeletons not being properly removed when loading index pages and softnav broken

blocks/cards/cards.js, blocks/pagination/pagination.js, templates/ask-author-page/ask-author-page.css, templates/ask-author-page/ask-author-page.js
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/tags/ask-dr-debra-common-questions
- After: https://fix-dr-debra-tag--petplace--hlxsites.hlx.live/tags/ask-dr-debra-common-questions
=> feat: add articles to dr debra tag page

templates/author-index/author-index.js, templates/author-page/author-page.css, templates/author-page/author-page.js
Test URLs:
- After:
- https://fix-author-pages--petplace--hlxsites.hlx.live/authors/
- https://fix-author-pages--petplace--hlxsites.hlx.live/authors/stephanie-silberstang-dvm-cva
- https://fix-author-pages--petplace--hlxsites.hlx.live/authors/dr-debra-primovic-dvm
=> feat: add author articles to their pages and fix index

blocks/header/header.js, blocks/search/search.js, templates/searchresults/searchresults.js
Adding `sampleRUM` instrumentation for search submissions and also logging no results.
- https://samplerum-search--petplace--hlxsites.hlx.live/search?query=ivermectin
- https://samplerum-search--petplace--hlxsites.hlx.live/search?query=impossible
=> feat: track search queries and results in RUM

scripts/scripts.js
Fix #271 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/dogs/pet-health/dog-health/dog-diet-nutrition/how-much-water-does-a-puppy-need
- After:
- https://issue-271--petplace--hlxsites.hlx.page/article/dogs/pet-health/dog-health/dog-diet-nutrition/how-much-water-does-a-puppy-need
=> bug: handle possible broken links and log with sampleRUM

blocks/article-navigation/article-navigation.js
Fix #284 #275
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/small-mammals/pet-care/small-pet-care/small-mammals/petplace-guide-hamster-cages
- After:
- https://issue-270-2--petplace--hlxsites.hlx.page/article/small-mammals/pet-care/small-pet-care/small-mammals/petplace-guide-hamster-cages
- https://issue-270-2--petplace--hlxsites.hlx.page/?martech=off/
=> fix: tracing to all parent categories if prev/next article not exist in own category

templates/article-page/article-page.css
Test URLs:
- After:
- https://<branch>--petplace--hlxsites.hlx.page/
- https://<branch>--petplace--hlxsites.hlx.page/?martech=off
=> fix: tap target sizes on mobile

blocks/footer/footer.css, blocks/form/form.js, blocks/newsletter-signup/newsletter-signup.css, blocks/newsletter-signup/newsletter-signup.js, scripts/scripts.js
Implements newsletter subscription functionality.
Added a new spreadsheet called `newsletter.xlsx` at the root of the project. The content of the newsletter form itself is driven by this spreadsheet.
A new block with two variants. The authoring experience is as follows:
The default variant will maintain a vertical layout. Eventually this block could be used in the pop-ups and on the newsletter signup page. Here is a rendered example at its widest:
The "horizontal" variant will behave as above on smaller resolutions, but will switch to a wider layout on bigger screens. This variant is used in the footer. Here is a rendered example when it's horizontal:
The block is also fully integrated with Iterable. I submitted my own email and received email confirmation for signing up for the …
=> feat: add newsletter subscription functionality

.github/ci/generate-news-feed.js, .github/ci/package-lock.json, .github/ci/package.json, .github/workflows/pre-build-search-index.yaml, head.html
Leverages the `feed` node module to build RSS & atom XML feeds for all articles. Those files are updated along with the search index when new articles are published.
=> feat: add RSS/Atom feed generation on article publishing

404.html, scripts/lib-franklin.js, scripts/worker/search.js, templates/searchresults/searchresults.js
As discussed with the customer:
- the 404 page should not redirect to the homepage but show a graceful error message instead
- the 404 page should act as a search page that will try to find articles related to the broken link
- aspx pages cannot be redirected client-side and were added to the `redirects.xslx` sheet
Test URLs:
- After:
- https://fix-404-page--petplace--hlxsites.hlx.live/reptiles/reptile-senses-understanding-their-world
- https://fix-404-page--petplace--hlxsites.hlx.live/reptiles/reptile-senses-understanding-their-world?martech=off
=> fix: 404 error page

templates/article-signup/article-signup.css, templates/article-signup/article-signup.js
There were some issues with the newsletter signup page on mobile, so this PR will improve all resolutions.
Fix #319 
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/drafts/frisbey/newsletter-signup
- After:
- https://issue-319-mobile--petplace--hlxsites.hlx.page/drafts/frisbey/newsletter-signup
- https://issue-319-mobile--petplace--hlxsites.hlx.page/drafts/frisbey/newsletter-signup?martech=off
=> feat: improve newsletter signup on mobile

.eslintrc.js, blocks/header/header.js, blocks/newsletter-signup/newsletter-signup.js, blocks/search/search.js, scripts/datalayer.js, scripts/scripts.js
Branch Commits :
- tracking search in header (ppl-17)
- tracking search in home page (ppl-17)
- tracking newsletter signups (ppl-23)
- tracking content category (ppl-25)
- added linting rule for default export
- importing function into files
- helper function to push to layer
- using proper terminology for layer
Jira Issues :
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-17
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-25
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-23
Test URLs:
- After:
- https://datalayer-ppl-17-23-25--petplace--hlxsites.hlx.page/
- …
=> Datalayer implementation for category, search and newsletter

.eslintrc.js, blocks/social-share/social-share.js, scripts/datalayer.js
Branch Commits :
- changes to href for consistency
- added eslint rule for ++ in for loops
- small changes to datalayer file
- handle article share push to DL
- added try catch block for console error
- change to foreach instead of for loop
Jira Issues :
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-19
Test URLs:
- After:
- https://datalayer-ppl-19--petplace--hlxsites.hlx.page/
- https://datalayer-ppl-19--petplace--hlxsites.hlx.page/?martech=off
=> Datalayer implementation for tracking article shares

.eslintignore, scripts/delayed.js, scripts/pushly-sdk-worker.js
Commits :
- got service worker file from cdn
- added sw script to pushly code
- added sw file to lint ignore
Jira Link : https://pethealthinc.atlassian.net/browse/PPL-26
Test URLs:
- After:
- https://ppl-26-pushly-sw--petplace--hlxsites.hlx.page/
- https://ppl-26-pushly-sw--petplace--hlxsites.hlx.page/?martech=off
=> feat: added pushly service worker

scripts/datalayer.js
Commits:
- change to article share to prevent warnings
- helper function to help with pushing data
- sending data for click events on headers
- fixed linting (whitespace) issues
Jira Issue:
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-18
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-43
Bugs Fixed:
Test URLs:
- After:
- https://datalayer-ppl-18-43--petplace--hlxsites.hlx.page/
- https://datalayer-ppl-18-43--petplace--hlxsites.hlx.page/?martech=off
=> Datalayer implementation for tracking header clicks

blocks/footer/footer.js, blocks/header/header.js, blocks/newsletter-signup/newsletter-signup.js, blocks/search/search.js, blocks/social-links/social-links.js, scripts/datalayer.js, scripts/utils/helpers.js
- change to article share to prevent warnings
- helper function to help with pushing data
- sending data for clicks on headers
- fixed linting (whitespace) issues
- added class to footer nav
- changing for better naming and targeting
- created helper file for external functions
- moved click helper func to utils file
- helper function to get social name
- moved social and nav funcs to helper file
- observing footer readiness
- added console logs for testing
- small changes to category tracked
Jira Issues:
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-42
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-45
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedI …
=> Datalayer implementation for footer and social links

scripts/third-party.js
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-47
Test URLs:
- After:
- https://gtag-ppl-47--petplace--hlxsites.hlx.live/
- https://gtag-ppl-47--petplace--hlxsites.hlx.live/?martech=off
=> added conversion snippet

scripts/datalayer.js, scripts/utils/helpers.js
Description : this branch covers work done on the header and footer tracking only
other items will be started on after this PR is merged in to ensure the right structure
Branch Commits :
- got rid for element clicks function
- removed footer helpers
- new function to track header clicks
- new function to track footer clicks
Jira Issue :
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-51
Test URLs:
- After:
- https://datalayer-refactor-ppl-51--petplace--hlxsites.hlx.page/
- https://datalayer-refactor-ppl-51--petplace--hlxsites.hlx.page/?martech=off
=> Datalayer refactor for global listener

.github/pull_request_template.md, scripts/datalayer.js, scripts/utils/helpers.js
Branch Commits :
- article sharing refactor
- tracking for cta buttons
- update to template to test against live link
Jira Issues :
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-44
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-19
Test URLs:
- After:
- https://datalayer-ppl-44-19--petplace--hlxsites.hlx.page/
- https://datalayer-ppl-44-19--petplace--hlxsites.hlx.page/?martech=off
=> Datalayer tracking for CTA buttons on homepage

scripts/datalayer.js, scripts/utils/helpers.js
Hotfix Targets:
- removing link helper from main
- removing article clicks from main
Commits:
https://github.com/hlxsites/petplace/commit/d944d10240f24882aee459a536379dd8b1ff6c39
https://github.com/hlxsites/petplace/commit/f2b7f6f2e84d0e25f2cb761bdf7896fbf6ab28da
Test URLs:
- After:
- https://hotfix-article-links--petplace--hlxsites.hlx.live/
- https://hotfix-article-links--petplace--hlxsites.hlx.live/?martech=off
=> Hotfix article links

scripts/datalayer.js, scripts/utils/helpers.js
- function and condition for article clicks
- helper function for hyperlink text
Jira Issues:
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-40
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-41
Test URLs:
- After:
- https://datalayer-ppl-40-41--petplace--hlxsites.hlx.live/
- https://datalayer-ppl-40-41--petplace--hlxsites.hlx.live/?martech=off
=> Datalayer implementation for article links

scripts/datalayer.js, scripts/utils/helpers.js
- created helper for popular posts
- function for tracking clicks on popular links
- checks in place to send the right text and type
Jira Issue:
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-49
Test URLs:
- After:
- https://datalayer-ppl-18-49--petplace--hlxsites.hlx.live/
- https://datalayer-ppl-18-49--petplace--hlxsites.hlx.live/?martech=off
=> Datalayer implementation for popular posts on article pages

scripts/datalayer.js, scripts/utils/helpers.js
- calling helper function in main datalayer thread
- helper function for prev/next articles
- conditions for clicks on text
- conditions for clicks on image
Jira Issue:
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-50
Test URLs:
- After:
- https://datalayer-ppl-18-50--petplace--hlxsites.hlx.live/
- https://datalayer-ppl-18-50--petplace--hlxsites.hlx.live/?martech=off
=> Datalayer implementation for previous/next articles

templates/article-signup/article-signup.css
Jira Issue: https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-53
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/newsletter-signup
- After:
- https://newsletter-page-design-changes--petplace--hlxsites.hlx.live/newsletter-signup
- https://newsletter-page-design-changes--petplace--hlxsites.hlx.live/newsletter-signup?martech=off
Screenshot:
=> added margin to create some space on paragraphs

ads.txt
Test URLs:
- After:
- https://adsense-ads-txt-file--petplace--hlxsites.hlx.live
- https://adsense-ads-txt-file--petplace--hlxsites.hlx.live/?martech=off
=> adding ads.txt file

scripts/third-party.js
- pushing gtag to generic datalayer
- new functions for gtm and noscripts
- function calls in delayed phase
Related Jira Issues:
https://pethealthinc.atlassian.net/browse/PM-19
Related PR (closed):
https://github.com/hlxsites/petplace/pull/354
Test URLs:
- After:
- https://issue-gtm-noscript--petplace--hlxsites.hlx.live/
- https://issue-gtm-noscript--petplace--hlxsites.hlx.live/?martech=off
=> fix: added gtm noscript tag

scripts/delayed.js, scripts/third-party.js, scripts/utils/adsense.js, styles/styles.css, templates/article-page/article-page.js, templates/category-index/category-index.js
- pushing up required styling first
- helper function for mapping and sizing
- dynamic div creator on the page
- function to define ad slots
- helper function for displaying ads
- loading ads in delayed phase for article
- loading ads in delayed phase for category
- changed condition to load gpt script
- fixed linting issues with logic operator
- some small changes to adsense helper file
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-21
Test URLs:
- After:
- https://feat-pm-21-adsense-article-category--petplace--hlxsites.hlx.live/
- https://feat-pm-21-adsense-article-category--petplace--hlxsites.hlx.live/?martech=off
Screenshots:
- Article page
- Category page (WIP)
=> feat: adsense for top and bottom of article and category

blocks/search/search.css, blocks/slideshow/slideshow.css
- changed h1 to h2 (pm-48)
- changed h2 to h1 (pm-49)
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-18
Test URLs:
- After:
- https://fix-pm-18-homepage-seo--petplace--hlxsites.hlx.live/
- https://fix-pm-18-homepage-seo--petplace--hlxsites.hlx.live/?martech=off
=> fix: homepage headers for seo

icons/long-arrow-down.svg, icons/long-arrow-up.svg, styles/styles.css, templates/insurance-landing-page/insurance-landing-page.css, templates/insurance-landing-page/insurance-landing-page.js
Jira Issue: [](https://pethealthinc.atlassian.net/browse/PM-73)
Test URLs:
- After:
- https://PM-73-new-insurance-landing-page--petplace--hlxsites.hlx.page/pet-insurance
- https://PM-73-new-insurance-landing-page--petplace--hlxsites.hlx.page/pet-insurance?martech=off
=> PM #73 -  PPL: Aggregator- Insurance Landing Page

templates/home-page/home-page.css
Jira ticket: [PM-71](https://pethealthinc.atlassian.net/browse/PM-71)
Test URLs:
- After:
- https://pm-71-home-carousel--petplace--hlxsites.hlx.page/
- https://pm-71-home-carousel--petplace--hlxsites.hlx.page/?martech=off
=> PM#71 - PPL: Aggregator - Homepage Carousel

scripts/adsense.js, scripts/utils/helpers.js, templates/article-page/article-page.js, templates/category-index/category-index.js
- changed ad sizing, ternary conditionals
- sending article category to datalayer
- sending category from page to datalayer
- fix a bug for uneven paras length
- set targeting from data layer
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-20
Test URLs:
- After:
- https://feat-pm-20-adsense-datalayer--petplace--hlxsites.hlx.live/
- https://feat-pm-20-adsense-datalayer--petplace--hlxsites.hlx.live/?martech=off
=> feat: adsense datalayer targeting

styles/styles.css, templates/insurance-landing-page/insurance-landing-page.css, templates/insurance-landing-page/insurance-landing-page.js
Jira ticket : [PM-73](https://pethealthinc.atlassian.net/browse/PM-73)
Test URLs:
- After:
- https://pm-73-bug-fixes--petplace--hlxsites.hlx.live/
- https://pm-73-bug-fixes--petplace--hlxsites.hlx.live/?martech=off
=> PM#73 - Bug fixes

icons/alert.svg, styles/styles.css, templates/home-page/home-page.css, templates/home-page/home-page.js, templates/insurance-landing-page/insurance-landing-page.css, templates/insurance-landing-page/insurance-landing-page.js
Jira Ticket: [PM-72](https://pethealthinc.atlassian.net/browse/PM-72)
Test URLs:
- After:
- https://pm-72-zipcode-component--petplace--hlxsites.hlx.page/
- https://pm-72-zipcode-component--petplace--hlxsites.hlx.page/?martech=off
=> PPL: Aggregator - Zip Code Component

helix-query.yaml, templates/author-index/author-index.js, templates/author-page/author-page.js
Add a new index for UK authors.
Test URLs:
- After:
- https://localized-authors--petplace--hlxsites.hlx.live/en-gb/authors/query-index.json
- https://localized-authors--petplace--hlxsites.hlx.live/en-gb/authors/query-index.json?martech=off
=> feat: properly localize author pages

scripts/datalayer.js
Jira Ticket - [PM#116](https://pethealthinc.atlassian.net/browse/PM-116)
Test URLs:
- After:
- https://pm-116-datalayer-enablement--petplace--hlxsites.hlx.live/
- https://pm-116-datalayer-enablement--petplace--hlxsites.hlx.live/?martech=off
=> PM#116 - PPL: Aggregator - Data Layer Enablement

styles/styles.css, templates/insurance-landing-page/insurance-landing-page.css
Jira Ticket - PM#73
Test URLs:
- After:
- https://pm-73-landing-page-update--petplace--hlxsites.hlx.live/
- https://pm-73-landing-page-update--petplace--hlxsites.hlx.live/?martech=off
=> PM#73 - New placement of figo powered text.

blocks/ad/ad.js, head.html, scripts/adsense.js, scripts/third-party.js
As per discussion with the team, we will be changing the GTM instrumentation to the traditional way and measuring the impact over a few months.
Test URLs:
- After:
- https://traditional-gtm--petplace--hlxsites.hlx.live/
- https://traditional-gtm--petplace--hlxsites.hlx.live/?martech=off
=> chore: instrument GTM the traditional way

templates/home-page/home-page.css, templates/insurance-landing-page/insurance-landing-page.css
Jira Ticket - PM#73
Test URLs:
- After:
- https://pm-73-ui-fixes--petplace--hlxsites.hlx.live/
- https://pm-73-ui-fixes--petplace--hlxsites.hlx.live/?martech=off
=> Pm 73 UI fixes

icons/alert.svg, icons/long-arrow-down.svg, icons/long-arrow-up.svg, scripts/adsense.js, scripts/datalayer.js, styles/styles.css, templates/home-page/home-page.css, templates/home-page/home-page.js, templates/insurance-landing-page/insurance-landing-page.css, templates/insurance-landing-page/insurance-landing-page.js
NOTE : THIS IS AN INDIE DEPLOYMENT TO MAIN
Sharepoint:
- `index.docx` and `pet-insurance.docx` are not live yet
- currently it's on `preview` and needs to be published
-----
Commits:
- PM#73 - PPL: Aggregator- Insurance Landing Page (#361) 
- PM#71 - PPL: Aggregator - Homepage Carousel (#363) 
- PM#73 - Bug fixes (#367) 
- PPL: Aggregator - Zip Code Component (#369) 
- PM#116 - PPL: Aggregator - Data Layer Enablement (#377) 
- PM#73 - New placement of figo powered text. (#379) 
- PM#73 UI fixes (#380) 
Jira Issues:
https://pethealthinc.atlassian.net/browse/PM-71
https://pethealthinc.atlassian.net/browse/PM-73
https://pethealthinc.atlassian.net/browse/PM-116
Test URLs:
- After:
- https://feat-aggregator-tool--petplace--hlxsites.hlx.live/ …
=> feat: aggregator tool deployment

README.md, scripts/adsense.js, scripts/utils/helpers.js, styles/styles.css, templates/article-page/article-page.js, templates/category-index/category-index.js
- reduced padding and removed gray background
- small changes to readme
- making sure to wait for divs to be finished first
- changed size for article middle ad
- changes to have it work for mobile and desktop
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-115
Test URLs:
- After:
- https://feat-adsense-mobile--petplace--hlxsites.hlx.live/
- https://feat-adsense-mobile--petplace--hlxsites.hlx.live/?martech=off
Screenshots:
desktop if no ad is displayed (background removed, only white space)
mobile ads showing up when loaded in mobile view (article)
mobile ads showing up when loaded in mobile view (category)
=> feat: mobile ads for article and category

scripts/delayed.js, scripts/third-party.js
Commit: remove condition for block ads checker
Note: need to publish `index.docx` as well on sharepoint
Related: #391
Test URLs:
- After:
- https://hotfix-homepage-ads-issue--petplace--hlxsites.hlx.page/
- https://hotfix-homepage-ads-issue--petplace--hlxsites.hlx.page/?martech=off
=> hotfix: change gpt script load condition

templates/insurance-landing-page/insurance-landing-page.css
NOTE: this needs to be deployed asap, so will be an indie deployment
Commits:
- linting and whitespace fixes
- added pumpkin logo and changed styling
- added styling to fix spacing on mobile
- made the sizing of other logos a bit more relative
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-127
Test URLs:
- After:
- https://feat-insurance-page-pumpkin--petplace--hlxsites.hlx.page/
- https://feat-insurance-page-pumpkin--petplace--hlxsites.hlx.page/?martech=off
Screenshots:
mobile
tablet
desktop
=> feat: pumpkin logo added to insurance page

.github/ci/build-search-index.js, .github/ci/utils.js, .github/workflows/pre-build-search-index.yaml, .github/workflows/run-tests.yaml, scripts/scripts.js, scripts/worker/search.js, templates/searchresults/searchresults.js
Test URLs:
- After:
- https://localized-search--petplace--hlxsites.hlx.live/en-gb/search
- https://localized-search--petplace--hlxsites.hlx.live/en-gb/search?martech=off
=> feat: add support for localized search

scripts/adsense.js, templates/article-page/article-page.js, templates/category-index/category-index.js, templates/home-page/home-page.js, templates/tag-index/tag-index.js
- creating tag divs and displaying ads
- refactored adsense functionality to be more streamlined
- using new adsense func for tag page
- using new adsense func for article page
- using new adsense func for home page
- using new adsense func for category page
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-89
Test URLs:
- After:
- https://feat-tag-page-ads--petplace--hlxsites.hlx.live/
- https://feat-tag-page-ads--petplace--hlxsites.hlx.live/?martech=off
Screenshots:
desktop
mobile
=> feat: ads for tag page + refactoring adsense

blocks/pet-details/pet-details.css
JIRA ticket PPAD-145
Fix pet profile font styles
Test URLs:
http://localhost:3000/pet-adoption/cats/46475081/PP914
=> bugfix: PPAD-150: pet-profile font styles

scripts/adsense.js
- removed the second/extra cmd push
- slight update to adsense setup function
- doing cmd push inside define slot function
- small refactor to main adsense function
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-128
Test URLs:
- After:
- https://bugfix-mobile-anchor-ads--petplace--hlxsites.hlx.live/
- https://bugfix-mobile-anchor-ads--petplace--hlxsites.hlx.live/?martech=off
Screenshots:
=> bugfix: anchor ads for mobile

head.html, scripts/scripts.js
Consent isn't properly picked up by google. we need to use the proper gtag method instead
=> fix: consent setup

scripts/adoption/favorite.js
Test URLs:
- Before: https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/
- After:
- [https://<branch>--petplace--hlxsites.hlx.live/](https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/)
- [https://<branch>--petplace--hlxsites.hlx.live/](https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/)?martech=off
=> return promise from both saveFavorite() and deleteFavorite() functions.

blocks/pet-details/pet-details.css
Fix #PPAD-155 - Style fixes for buttons on profile page to avoid horizontal scroll on mobile
Test URLs:
- Before: https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/dogs/38343517/194929
- After:
- http://localhost:3000/pet-adoption/cats/46475081/PP914
Proof: 
Please make sure to test it using a real device.
=> [PPAD-155] [QA] - Pet Profile - The "slides navigation" of the mobile version is not centered

scripts/adsense.js, scripts/utils/helpers.js, templates/breed-index/breed-index.js, templates/breed-page/breed-page.css, templates/breed-page/breed-page.js
This deployment includes:
- bugfix: anchor ads for mobile (#412)
- feat: adsense display for uk locale (#413)
- feat: ads for breed guide and single breed pages (#419)
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-128
https://pethealthinc.atlassian.net/browse/PM-151
https://pethealthinc.atlassian.net/browse/PM-130
Test URLs:
- After:
- https://sprint5-deploy--petplace--hlxsites.hlx.live/
- https://sprint5-deploy--petplace--hlxsites.hlx.live/?martech=off
=> deployment for sprint 5

blocks/account/account-favorites.js, blocks/account/account.css, blocks/account/account.js
Fix #PPAD-63
Test URLs:
- http://localhost:3000/pet-adoption/account > click on favorites panel
=> [PPAD-63] Account - Favorite Animals Page

blocks/account/account-details.js, head.html, scripts/lib/msal/msal-authentication.js, scripts/lib/msal/msal-instance.js, scripts/scripts.js
Test URLs:
- Before: https://hero-develop--petplace--hlxsites.hlx.page/
- After:
- [https://feature-msal-performance-refactor--petplace--hlxsites.hlx.live/](https://feature-msal-performance-refactor--petplace--hlxsites.hlx.page/)
- [https://feature-msal-performance-refactor--petplace--hlxsites.hlx.live/](https://feature-msal-performance-refactor--petplace--hlxsites.hlx.page/)?martech=off
=> dynamically load msal.js only when it is needed.

blocks/genai-search/genai-search.css, blocks/genai-search/genai-search.js, blocks/header/header.css, scripts/delayed.js, templates/gen-ai/gen-ai.js
Adding fixes for the clear button in the search input, genai button position updates, and clearing local storage item containing search query after successful search.
Fix #PM-15
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/discovery
- After:
- https://pm-15-genai-updates--petplace--hlxsites.hlx.live/discovery?martech=off
- https://pm-15-genai-updates--petplace--hlxsites.hlx.live/article/cats/pet-health/reverse-sneezing-in-cats?martech=off
=> Pm 15 genai updates

blocks/adopt-checklist/adopt-checklist.css, blocks/pet-details/pet-details.css
[PPAD-168] [QA] - Adoption Checklist - The color of the ‘dogs’ and 'cats' texts doesn't match the Figma design
[PPAD-263] [QA] - Pet Profile - The "Favorites" button label is not centered in the mobile version
Test URLs:
- Before: 
https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/checklist
https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/dogs/38343517/194929
- After:
http://localhost:3000/pet-adoption/checklist
http://localhost:3000/pet-adoption/dogs/38343517/194929
=> [PPAD-168] [PPAD-263] 

templates/insurance-landing-page/insurance-landing-page.css
css modifications for extra logo
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-159
Test URLs:
- After:
- https://feat-insurance-landing-embrace--petplace--hlxsites.hlx.page/
- https://feat-insurance-landing-embrace--petplace--hlxsites.hlx.page/?martech=off
Screenshots:
=> feat: embrace logo added to insurance landing

scripts/lib/msal/msal-authentication.js
Test URLs:
- After:
- https://main--petplace--hlxsites.hlx.live/
- https://main--petplace--hlxsites.hlx.live/?martech=off
=> read from template meta tag.

blocks/account/account.css
Test URLs:
http://localhost:3000/pet-adoption/account
=> [PPAD-276] [QA] - Mobile - My Accounts - Search Alerts - Delete search confirmation button

blocks/header/header.js, scripts/lib/msal/default-msal-config.js
Updated redirect urls after logout to point to homepage. Removed console.log statement.
=> [PPAD-295] [QA] - Main Nav - Logout issue

blocks/account/account-details.js, blocks/account/account-favorites.js, blocks/account/account-saved-searches.js, blocks/account/tabs-manual.js, scripts/lib/msal/msal-authentication.js
Added verification to check if user is logged in begore doing updates on user data to avoid changing user data when user logged out.
Test URLs:
http://localhost:3000/pet-adoption/account
=> PPAD-297   [QA] - Able to delete search criteria even after logout

blocks/pet-details/pet-details.js
=> change placeholders path

blocks/header/header.css
=> removing language selector

blocks/tiles/tiles.js
=> fix: website name leaking in tiles titles

blocks/header/header.css
Fixing the Gen-AI floating icon so it shows up on the Article/Blog Pages once again
Fix #PM-15
Test URLs:
- Before: https://www.petplace.com/article/dogs/pet-health/dog-health/what-to-expect-after-neutering-a-dog
- After:
-https://pm-15-genai-fixes--petplace--hlxsites.hlx.page/article/dogs/pet-health/dog-health/what-to-expect-after-neutering-a-dog
=> Fixing Gen-AI floating icon

blocks/header/header.css, templates/gen-ai/gen-ai.js
Fix for Gen-AI Search page not functioning after asking a question from the blog/article pages
Fix #PM-15
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/discovery
- After:
- https://pm-15-genai-query--petplace--hlxsites.hlx.page/discovery
=> Pm 15 genai query

blocks/pet-details/pet-details.css
Fixed style on PDP grid.
Test URLs:
- Before: https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/cats/39296934/PP29
- After:
http://localhost:3000/pet-adoption/cats/39296934/PP29
=> [PPAD-272] [QA} - Mobile - Pet profile view - Pet details getting cut

blocks/account/account-details.js, blocks/account/account-inquiries.js, blocks/account/account.css
Test URLs:
http://localhost:3000/pet-adoption/account
=> [PPAD-308] Account - Details - Remove search alerts when disabling e-mail consent

templates/insurance-landing-page/insurance-landing-page.css
Fix #PM-222
Test URLs:
- After:
- https://pm-222-remove-akc--petplace--hlxsites.hlx.live/
- https://pm-222-remove-akc--petplace--hlxsites.hlx.live/?martech=off
=> PPL: Remove AKC from insurance landing page

blocks/account/account-details.js, blocks/account/account.css, blocks/adopt-search-results/adopt-search-results.css, blocks/adopt-search-results/adopt-search-results.js, scripts/adoption/saveSearch.js, scripts/lib/msal/login-redirect-handlers.js
Test URLs:
- http://localhost:3000/pet-adoption/search?milesRadius=10&filterGender=&filterAge=&filterAnimalType=null&filterBreed=&zipPostal=33472&filterSize=
=> [PPAD-307] Account - Search Alert - Check e-mail preference on search alert creation

blocks/account/account-details.js, blocks/account/account-favorites.js, blocks/account/account-saved-searches.js, blocks/adopt-search-results/adopt-search-results.js, blocks/pet-details/pet-details.js, scripts/adoption/errorPage.js, scripts/adoption/favorite.js, scripts/adoption/saveSearch.js, styles/styles.css
=> [PPAD-126] Error handling screens for API calls

blocks/genai-search/genai-search.js, templates/adoption-landing-page/adoption-landing-page.css, templates/article-page/article-page.js, templates/gen-ai/gen-ai.js
These fixes include an update to remove whitespace around the hero image on the Worth The Wait landing page. Additionally it includes the addition of datalayer calls within the GenAI experience.
Fix # PM-239
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/worth-the-wait
- After: https://pm-239--petplace--hlxsites.hlx.page/worth-the-wait
=> Pm 239 - Adoption Landing Page and GenAI Tracking

blocks/account/tabs-manual.js
In addition to these changes we also updated mega-nav doc. **These changes are on preview mode.** After QA finished testing we should **publish** them.
Account Details -> url updated to "https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/account#details"
Search Alerts -> item added - url: "https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/account#searchalerts"
Favorite Animals -> item added - url: "https://hero-develop--petplace--hlxsites.hlx.page/pet-adoption/account#favorites"
Test URLs:
- http://localhost:3000/pet-adoption/account#searchalerts
- http://localhost:3000/pet-adoption/account#favorites
=> [PPAD-333] Link Saved Search and Favorite page under the profile button in header

blocks/account/account-saved-searches.js, blocks/account/account.css, scripts/adoption/saveSearch.js
Test URLs:
- http://localhost:3000/pet-adoption/account#searchalerts
=> [PPAD-217] Account - Additional Details on Saved Searches

blocks/panel-cards/panel-cards.css, blocks/panel-cards/panel-cards.js, blocks/slideshow/slideshow.css
Added structure and styles for pet place adoption carousel and table panels cards.
Test URLs:
- http://localhost:3000/pet-adoption/ 
Screenshots:
=> [PPAD-260] Main Nav - Image Carousel

blocks/inquiry-confirmation/inquiry-confirmation.js, blocks/pet-survey/pet-survey.js, blocks/survey-confirmation/survey-confirmation.js
Fixing path to placeholders
Test URLs:
- Before: https://www.petplace.com/pet-adoption/survey?animalId=55592069&clientId=PP2407&animalType=dog
- After:
- https://www.petplace.com/pet-adoption/survey?animalId=55592069&clientId=PP2407&animalType=dog
=> fixing path for placeholders url

blocks/pet-survey/pet-survey.css
Fixed styles for pet survey - mobile.
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/pet-adoption/survey?animalType=cat 
- After:
- http://localhost:3000/pet-adoption/survey?animalType=cat
=> [PPAD-402] [QA] - Mobile - Survey - The survey form fields are cut while filling the survey

scripts/lib/msal/msal-authentication.js
Fixed login and user buttons show up and hide when user is logged in.
Test URLs:
- http://localhost:3000/pet-adoption/search?milesRadius=10&filterGender=&filterAge=&filterAnimalType=Dog&filterBreed=&filterShelter=&zipPostal=33472&filterSize=
=> [PPAD-332] [QA] - Login Button Persisting after Successful Login

blocks/adopt-search-results/adopt-search-results.css, scripts/adoption/saveSearch.js
Created logic to show modal with specific message when user tries to create a duplicated search.
Test URLs:
- http://localhost:3000/pet-adoption/search
- http://localhost:3000/pet-adoption/account#searchalerts
Note: The following labels were created on placeholders.xslx file, they can be replaced as the client's wishes. These changes are currently on **preview** mode and at some point this needs to be **published**.
=> [PPAD-243] [QA] - Search Page - Save same search criteria

templates/gen-ai/gen-ai.js
hide placeholder when insurance is searched
=> PM-227: Adobe GenAI - Insurance Search

blocks/header/header.css, blocks/header/header.js
- made the nav sticky
- extended nav to full width
- removed transparent background
- close dropdown on scroll
- fix overlapping issue on scroll
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-253
Test URLs:
- After:
- https://feat-sticky-nav--petplace--hlxsites.hlx.live/
- https://feat-sticky-nav--petplace--hlxsites.hlx.live/?martech=off
=> feat: sticky nav bar (mobile/desktop)

blocks/header/header.css, blocks/header/header.js, templates/gen-ai/gen-ai.js
Deployment includes:
- PM-227: Adobe GenAI - Insurance Search (#490) 
- feat: sticky nav bar (mobile/desktop) (#491)
Related Jira Tickets:
https://pethealthinc.atlassian.net/browse/PM-227
https://pethealthinc.atlassian.net/browse/PM-253
Test URLs:
- After:
- https://sprint9-deploy--petplace--hlxsites.hlx.live/
- https://sprint9-deploy--petplace--hlxsites.hlx.live/?martech=off
=> deployment for sprint 9

blocks/pet-survey/pet-survey.css, blocks/pet-survey/pet-survey.js
Fix #PPAD-421
Test URLs:
http://localhost:3000/pet-adoption/survey?animalId=30779404&clientId=PP2407&animalType=dog
=> [PPAD-421]: Show Previous inquiry submitted modal

blocks/adopt-search-results/adopt-search-results.js
Fix #PPAD-244
Test URLs:
http://localhost:3000/pet-adoption/search?milesRadius=10&filterGender=M&filterAge=&filterAnimalType=Dog&filterBreed=&filterShelter=&zipPostal=19121&filterSize=
=> PPAD-244: keep filters on pet type change tt

blocks/pet-survey/pet-survey.js
=> PPAD-411 disable save changes after submit survey tt

blocks/newsletter-signup/newsletter-signup.css
Commit: adding button back to grid
Test URLs:
- After:
- https://newsletter-footer-btn-issue--petplace--hlxsites.hlx.live/
- https://newsletter-footer-btn-issue--petplace--hlxsites.hlx.live/?martech=off
Screenshot
- issue
- fixed
=> hotfix: newsletter footer button issue

blocks/adopt-search-results/adopt-search-results.js
=> [PPAD-422]: Show results when user does not select a pet type on search

blocks/account/account.css
Fix #PPAD-406
http://localhost:3000/pet-adoption/account#details
=> [PPAD-406] - Mobile inquiry button text trimmed

blocks/home-banner/home-banner.css
Fix PM-336
Test URLs:
- After:
- https://pm-336-homeage-hero-image-fix--petplace--hlxsites.hlx.live/
- https://pm-336-homeage-hero-image-fix--petplace--hlxsites.hlx.live/?martech=off
=> PM #336 -Homepage Template - Hero Image

blocks/home-banner/home-banner.css, blocks/home-banner/home-banner.js, blocks/tiles/tiles.css, blocks/tiles/tiles.js
Fix PM#97
Test URLs:
- After:
- https://pm-97-image-clickability--petplace--hlxsites.hlx.live/
- https://pm-97-image-clickability--petplace--hlxsites.hlx.live/?martech=off
=> PM#97 - Homepage - Image Clickability

blocks/newsletter-signup/newsletter-signup.css, blocks/panel-cards/panel-cards.css, blocks/panel-cards/panel-cards.js, blocks/tiles/tiles.css, scripts/adsense.js, templates/home-page/home-page.css, templates/home-page/home-page.js
- small changes to home page tiles styling
- added explore panel to home page
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-199
Test URLs:
- After:
- https://feature-homepage-explore-tiles--petplace--hlxsites.hlx.page/
- https://feature-homepage-explore-tiles--petplace--hlxsites.hlx.page/?martech=off
=> feat: homepage explore tiles

templates/insurance-page/insurance-page.css, templates/insurance-page/insurance-page.js
Fix: [PM-339](https://pethealthinc.atlassian.net/browse/PM-339)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california
- After:
- https://bugfix-insurance-page-table--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california
- https://bugfix-insurance-page-table--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california?martech=off
=> Bugfix: insurance page table

blocks/panel-cards/panel-cards.css, blocks/panel-cards/panel-cards.js, templates/home-page/home-page.css
- small change to panel title as per figma
- panel box is clickable (similar to pm-97)
Related to (#520) and comments on below jira ticket
https://pethealthinc.atlassian.net/browse/PM-199
Test URLs:
- After:
- https://bugfix-small-changes-for-deploy--petplace--hlxsites.hlx.live/
- https://bugfix-small-changes-for-deploy--petplace--hlxsites.hlx.live/?martech=off
=> bugfix: small changes for indie deploy

blocks/home-banner/home-banner.css, blocks/home-banner/home-banner.js, blocks/panel-cards/panel-cards.css, blocks/panel-cards/panel-cards.js, blocks/tiles/tiles.css, blocks/tiles/tiles.js, icons/chevron-large.svg, scripts/adsense.js, scripts/scripts.js, styles/styles.css, templates/author-page/author-page.js, templates/home-page/home-page.css, templates/home-page/home-page.js, templates/insurance-page/insurance-page.css, templates/insurance-page/insurance-page.js
Pages to publish:
- https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/doc2.aspx?sourcedoc=%7B09855470-66CA-4C7A-965C-4A1C7A79B5F8%7D&file=index.docx&action=default&mobileredirect=true
Deployment includes:
- PM#97 - Homepage - Image Clickability (#518) 
-  (pm-199) feat: homepage explore tiles (#519)
- feat(PM-331): Add breadcrumbs to Insurance Pages (#516) 
- PM #336 -Homepage Template - Hero Image (#514) 
- (pm-339) Bugfix: insurance page table (#512)
- (pm-340) bugfix: homepage iphone issues (#515)
- bugfix: small changes for indie deploy (#521)
- 
Jira Issues
- https://pethealthinc.atlassian.net/browse/PM-97
- https://pethealthinc.atlassian.net/browse/PM-199
- https://pethealthinc.atlassian.net/browse/PM-331
- https://pethealthinc.atlassian.net/browse/PM-336 
- …
=> indie deployment for sprint 12

blocks/account/account-favorites.js, blocks/account/account-inquiries.js, blocks/account/account.css
Fix #PPAD-404
/pet-adoption/account#details
=> [PPAD-404] - Account Favorites and Inquiries cards fit image

blocks/pet-details/pet-details.css
Description: Mobile button for start pet match survey now fits in the container, as well as the table version were it was getting off the card too.
Fix #PPAD-407
Mobile
Tablet
=> PPAD-407: Pet details button alignment fix

blocks/pet-details/pet-details.css
Reduce padding on mobile view for start survey button
Fix #525 
Test URLs:
- After:
=> [PPAD-407]: Reduce button padding on mobile view

blocks/adopt-search-results/adopt-search-results.css, blocks/adopt-search-results/adopt-search-results.js
Use grid layout to match easly the figma designs for tablet 
Fix #PPAD-134
Test URLs:
- After:
=> PPAD-134:  Match filters design layout for tablet

blocks/adopt-search-results/adopt-search-results.js
Fix #PPAD-426
Test URLs:
- After:
=> [PPAD-26]:  Do not scroll after shelter selection on mobile

blocks/adopt-search-results/adopt-search-results.css
Remove sidebar absolute position and implement grid layout in results 
Fix #PPAD-424
Test URLs:
- After:
=> PPAD-424: Remove sidebar absolute position and implement grid layout in results 

scripts/scripts.js
Fix #
Test URLs:
- After:
- https://22691-track-region-in-rum--petplace--rachel-kittens.hlx.page/
- https://22691-track-region-in-rum--petplace--rachel-kittens.hlx.page/?martech=off
=> [SITES-22691] Track user region source in RUM data

scripts/scripts.js
Fix #
Test URLs:
- After:
- https://22691-track-lang-in-rum--petplace--rachel-kittens.hlx.live/
- https://22691-track-lang-in-rum--petplace--rachel-kittens.hlx.live/?martech=off
=> [SITES-22691] Track user language source and target in RUM data

scripts/scripts.js
Fix #
Test URLs:
- After:
- https://22691-change-audiences-to-variant--petplace--hlxsites.hlx.live
- [https://<branch>--petplace--hlxsites.hlx.live](https://22691-change-audiences-to-variant--petplace--hlxsites.hlx.live)/?martech=off
=> [SITES-22691] Change checkpoint 'audiences' to 'variant'

blocks/panel-cards/panel-cards.css, blocks/panel-cards/panel-cards.js
https://pethealthinc.atlassian.net/browse/PM-384
Test URLs:
- After:
- https://bugfix-homepage-panels--petplace--hlxsites.hlx.live/
- https://bugfix-homepage-panels--petplace--hlxsites.hlx.live/?martech=off
Screenshots
=> used panel card code from earlier

blocks/footer/footer.css
Fix #346
Test URLs:
- After:
- https://pm-346-figo-disclaimer-footer--petplace--hlxsites.hlx.page/
- https://pm-346-figo-disclaimer-footer--petplace--hlxsites.hlx.page/?martech=off
=> PM#346 - Add Figo Disclaimer to Sitewide Footer

ads.txt
Fix PM-389
Test URLs:
- After:
- https://pm-389-replace-ads-txt--petplace--hlxsites.hlx.page/
- https://pm-389-replace-ads-txt--petplace--hlxsites.hlx.page/?martech=off
=> PM#389 - PPL: Replace ads.txt File

ads.txt
Reverts hlxsites/petplace #545
=> Revert "PM#389 - PPL: Replace ads.txt File"

templates/home-page/home-page.css, templates/home-page/home-page.js
Fix #344
Test URLs:
- After:
- https://pm-344-aggrator-widget--petplace--hlxsites.hlx.live/
- https://pm-344-aggrator-widget--petplace--hlxsites.hlx.live/?martech=off
=> PM#344 - Homepage - P3 Aggregator Widget

blocks/article-pagination/article-pagination.css, blocks/article-pagination/article-pagination.js, blocks/cards/cards.css, blocks/cards/cards.js, blocks/popular-tags/popular-tags.css, blocks/popular-tags/popular-tags.js, scripts/adsense.js, styles/styles.css, templates/category-index/category-index.css, templates/category-index/category-index.js, templates/insurance-page/insurance-page.js
Provides updates to the Category template as per requirements.
Fix: [PM-277](https://pethealthinc.atlassian.net/browse/PM-277)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/category/pet-health
- After:
- https://feat-category-template-update--petplace--hlxsites.hlx.page/article/category/pet-health
- https://feat-category-template-update--petplace--hlxsites.hlx.page/article/category/pet-health?martech=off
=> feat(PM-277): Category template update

ads.txt, blocks/article-pagination/article-pagination.css, blocks/article-pagination/article-pagination.js, blocks/cards/cards.css, blocks/cards/cards.js, blocks/footer/footer.css, blocks/popular-tags/popular-tags.css, blocks/popular-tags/popular-tags.js, scripts/adsense.js, styles/styles.css, templates/category-index/category-index.css, templates/category-index/category-index.js, templates/home-page/home-page.css, templates/home-page/home-page.js, templates/insurance-page/insurance-page.js
Features Deployed
PM#346 - Add Figo Disclaimer to Sitewide Footer (#543) 
PM#344 - Homepage - P3 Aggregator Widget (#527) 
feat(PM-277): Category template update (#537) 
Jira Issues
https://pethealthinc.atlassian.net/browse/PM-346
https://pethealthinc.atlassian.net/browse/PM-344
https://pethealthinc.atlassian.net/browse/PM-277
Test URLs:
- After:
- https://sprint13-deploy--petplace--hlxsites.hlx.live/
- https://sprint13-deploy--petplace--hlxsites.hlx.live/?martech=off
=> Sprint13 deploy

templates/article-page/article-page.css, templates/article-page/article-page.js
Jira Ticket: https://pethealthinc.atlassian.net/browse/PM-310
Test URLs:
- After:
- https://feat-new-article-template-title-hero-author--petplace--hlxsites.hlx.live/
- https://feat-new-article-template-title-hero-author--petplace--hlxsites.hlx.live/?martech=off
=> title, author and hero design modified according to figma

templates/insurance-landing-page/insurance-landing-page.js
Branch Commit:
aggregator url updated
Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-406
Test URLs:
- After:
- https://feat-aggregator-widget-update--petplace--hlxsites.hlx.live/
- https://feat-aggregator-widget-update--petplace--hlxsites.hlx.live/?martech=off
=> feat: aggregator url changed for a/b test

react-client/src/components/design-system/button/LinkIconButton.test.tsx, react-client/src/components/design-system/button/LinkIconButton.tsx, react-client/src/components/design-system/button/__snapshots__/LinkIconButton.test.tsx.snap
This PR is responsible to create the LinkIconButton and its unit tests;
Test URLs:
- After:
- https://80918-create-link-icon-button--petplace--hlxsites.hlx.live/
- https://80918-create-link-icon-button--petplace--hlxsites.hlx.live/?martech=off
=> 80918 Create link icon button

blocks/genai-search/genai-search.css, scripts/adsense.js, scripts/datalayer.js, scripts/utils/helpers.js, templates/article-page/article-page.css, templates/article-page/article-page.js
- adding gen ai back in
- adding attribute setting back
- setting up content alignment
- css changes for grid layout
- changes for divs attached to ads
- breadcrumbs added to page
- minor changes to element positioning
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-343
Test URLs:
- After:
- https://feat-new-article-page-alignment--petplace--hlxsites.hlx.live/
- https://feat-new-article-page-alignment--petplace--hlxsites.hlx.live/?martech=off
=> page alignment for grid in mobile and desktop

blocks/widget-aggregator/widget-aggregator.css, blocks/widget-aggregator/widget-aggregator.js, templates/insurance-page/insurance-page.css, templates/insurance-page/insurance-page.js
- Remove hard-coded injection from insurance template
- Add as a block with authorable source and noLegal status
Test URLs:
- After:
- https://feat-insurance-dynamic-widget--petplace--hlxsites.hlx.page/
- https://feat-insurance-dynamic-widget--petplace--hlxsites.hlx.page/?martech=off
=> feat(PM-390): Implement dynamic widget aggregator as a block

blocks/article-cta/article-cta.css, blocks/article-cta/article-cta.js, blocks/popular-articles/popular-articles.js, blocks/related-reading/related-reading.css, blocks/related-reading/related-reading.js, blocks/social-share/social-share.js, templates/article-page/article-page.css, templates/article-page/article-page.js
- removed double border on cta
- removed date and author from popular
- removed date and author from related
- removed twitter from social share
- fixed alignment for socials, breadcrumb and related
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-278
Test URLs:
- After:
- https://feat-new-article-template-small-fixes--petplace--hlxsites.hlx.page/
- https://feat-new-article-template-small-fixes--petplace--hlxsites.hlx.page/?martech=off
=> small fixes for article template before prod

blocks/genai-search/genai-search.css, blocks/popular-articles/popular-articles.css, templates/article-page/article-page.css, templates/article-page/article-page.js
- changed css to not affect other heading tags
- small fixes to popular cards alignment
- removed load block from create template fn
- small changes to breadcrumb
- css changes to article page
Jira Ticket
https://pethealthinc.atlassian.net/browse/PM-278
Test URLs:
- After:
- https://feat-new-article-template-final-fixes--petplace--hlxsites.hlx.live/
- https://feat-new-article-template-final-fixes--petplace--hlxsites.hlx.live/?martech=off
=> final fixes for the article page template

blocks/article-author/article-author.js, blocks/article-cta/article-cta.js, blocks/related-reading/related-reading.js, scripts/scripts.js, templates/article-page/article-page.css
- made cta link clickable
- removed extra info from related reading
- hiding section if no related articles present
- hide avatar if no image present
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-278
Test URLs:
- After:
- https://feat-new-article-template-last-fixes--petplace--hlxsites.hlx.page/
- https://feat-new-article-template-last-fixes--petplace--hlxsites.hlx.page/?martech=off
=> final fixes for the article template

blocks/header/header.css, blocks/header/header.js, scripts/scripts.js, scripts/third-party.js
Test URLs:
- After:
- https://delayed-martech--petplace--hlxsites.hlx.live/
- https://delayed-martech--petplace--hlxsites.hlx.live/?martech=off
=> refactor: delay the martech stack

templates/insurance-landing-page/insurance-landing-page.js
Related to #602
Test URLs:
- After:
- https://bugfix-update-aggregator-url--petplace--hlxsites.hlx.live/
- https://bugfix-update-aggregator-url--petplace--hlxsites.hlx.live/?martech=off
=> bugfix: changed back to original url

blocks/home-banner/home-banner.js, blocks/panel-cards/panel-cards.js, scripts/datalayer.js, templates/article-page/article-page.css
- datalayer for hero banner
- datalayer for home panels
- changes to banner clicking
- added para breaks to article (pm430)
- click added for mobile and desktop divs
- changed closest target for image clicks
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-409
https://pethealthinc.atlassian.net/browse/PM-430
Test URLs:
- After:
- https://feat-home-panels-datalayer--petplace--hlxsites.hlx.live/
- https://feat-home-panels-datalayer--petplace--hlxsites.hlx.live/?martech=off
=> feat: datalayer for home panels

blocks/related-reading/related-reading.js
Test URLs:
- After:
- https://fix-related-articles--petplace--hlxsites.hlx.live/article/general/pet-care/dog-care/dog-adoption/the-reasons-to-adopt-a-pet-instead-of-buying-one
- https://fix-related-articles--petplace--hlxsites.hlx.live/article/general/pet-care/dog-care/dog-adoption/the-reasons-to-adopt-a-pet-instead-of-buying-one?martech=off
=> fix: related articles logic following new indexing mechanism

templates/ask-author-page/ask-author-page.css, templates/ask-author-page/ask-author-page.js
**Issue:** On this page only([Ask Dr. Debra Common Questions | Petplace](https://www.petplace.com/tags/ask-dr-debra-common-questions)), the layout appears very skewed, due to it pulling in CSS from the Popular Tags template.
Fix: [PM-454](https://pethealthinc.atlassian.net/browse/PM-454)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/tags/ask-dr-debra-common-questions
- After:
- https://bugfix-tag-page-template--petplace--hlxsites.hlx.page/tags/ask-dr-debra-common-questions
- https://bugfix-tag-page-template--petplace--hlxsites.hlx.page/tags/ask-dr-debra-common-questions/?martech=off
=> fix: Tag Page Template - Layout Issue

blocks/related-reading/related-reading.js
Test URLs:
- After:
- https://fix-related-readings--petplace--hlxsites.hlx.live/article/general/pet-care/7-myths-shelter-pets
- https://fix-related-readings--petplace--hlxsites.hlx.live/article/general/pet-care/7-myths-shelter-pets?martech=off
=> fix: update related readings block to new index

templates/insurance-landing-page/insurance-landing-page.css
Pages: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/doc2.aspx?sourcedoc=%7B0D236D0A-EB13-46D1-AB5B-A7C3475C2BAB%7D&file=pet-insurance.docx&action=default&mobileredirect=true
Jira Tickets:
https://pethealthinc.atlassian.net/browse/PM-320
https://pethealthinc.atlassian.net/browse/PM-428
Test URLs:
- After:
- https://feat-insurance-landing-new-logos--petplace--hlxsites.hlx.page/
- https://feat-insurance-landing-new-logos--petplace--hlxsites.hlx.page/?martech=off
Screenshots:
desktop
mobile
tablet
=> changed sizing/placement of logos

ads.txt, blocks/article-pagination/article-pagination.js, blocks/social-share/social-share.js, blocks/tiles/tiles.css, blocks/widget-aggregator/widget-aggregator.css, templates/breed-page/breed-page.css, templates/category-index/category-index.js
- cleared observer error on pagination (pm-404)
- hide skeleton for extra articles (pm-405)
- hiding title for state insurance pages (pm-446)
- fixed width on tiles (pm-457)
- adjusting background after removing extra space (pm-456)
- removed extra pagination observer (pm-404)
- controlling widget margin (pm-456)
- updated ads.txt file (pm-452)
- fixed width issue for all articles on home page (pm-457)
- fix widget margin for breed page (pm-456)
- changed bg color of section (pm-456)
Jira Tickets:
- https://pethealthinc.atlassian.net/browse/PM-404
- https://pethealthinc.atlassian.net/browse/PM-405
- https://pethealthinc.atlassian.net/browse/PM-446
- https://pethealthinc.atlassian.net/browse/PM-456
- https://pethealthinc.atlassian.net/browse/PM-457
- …
=> bugfix: category, insurance, breed pages

blocks/cards/cards.js, templates/category-index/category-index.js
Test URLs:
- After:
- https://fix-category-index-cls2--petplace--hlxsites.hlx.live/article/category/pet-care/cat-care
- https://fix-category-index-cls2--petplace--hlxsites.hlx.live/article/category/pet-care/cat-care?martech=off
=> fix(perf): start article loading early to speed up the LCP

templates/category-index/category-index.js
Test URLs:
- After:
- https://fix-tag-index-cls--petplace--hlxsites.hlx.live/
- https://fix-tag-index-cls--petplace--hlxsites.hlx.live/?martech=off
=> fix(perf): tag index page cls

templates/insurance-landing-page/insurance-landing-page.css
PPL: Insurance Page - Hero Banner Layout:
Fix PM-425](https://pethealthinc.atlassian.net/browse/PM-425)
Test URLs:
- After:
- [https://pm-425-v2--petplace--hlxsites.hlx.page/pet-insurance](https://pm-425-v2--petplace--hlxsites.hlx.page/pet-insurance)
- [https://pm-425-v2--petplace--hlxsites.hlx.page/pet-insurance/?martech=off](https://pm-425-v2--petplace--hlxsites.hlx.page/pet-insurance)
=> Adjust hero image cropping on wider screens

react-client/.eslintrc.cjs, react-client/package.json
Test URLs:
- After:
- https://eslint-improvements--petplace--hlxsites.hlx.live/
- https://eslint-improvements--petplace--hlxsites.hlx.live/?martech=off
=> feat: improve eslint for better development

blocks/genai-search/genai-search.css, templates/gen-ai/gen-ai.js
PM-464: gen-ai title layout/slideshow responsive layout updates
PM-463: genai suggested articles swiping updates
Test URLs:
- After:
- https://hotfixes-genai-s16--petplace--hlxsites.hlx.live/
- https://hotfixes-genai-s16--petplace--hlxsites.hlx.live/?martech=off
=> hotfix: genai bugs leftover from sprint16

react-client/src/components/Pet/PetAlertMessage.test.tsx, react-client/src/components/Pet/PetAlertMessage.tsx, react-client/src/components/Pet/sections/AdvertisingSection.tsx, react-client/src/components/Pet/sections/PetAlertSection.tsx, react-client/src/components/Pet/sections/PetCardSection.tsx, react-client/src/components/Pet/sections/PetInsurancecSection.tsx, react-client/src/routes/my-pets/:petId/PetLostUpdates.tsx, react-client/src/routes/my-pets/:petId/PetProfileIndex.tsx
Test URLs:
- After:
- https://82268-add-banner--petplace--hlxsites.hlx.live/
- https://82268-add-banner--petplace--hlxsites.hlx.live/?martech=off
=> 82268 add banner

react-client/src/mocks/MockRestApiServer.ts, react-client/src/routes/AppRoute.tsx, react-client/src/routes/AppRoutePaths.ts, react-client/src/routes/checkout/CheckoutIndex.tsx, react-client/src/routes/checkout/useCheckoutIndexViewModel.tsx
create the basic checkout route
Test URLs:
- After:
- https://82363-checkout-route--petplace--hlxsites.hlx.live/
- https://82363-checkout-route--petplace--hlxsites.hlx.live/?martech=off
=> feat: create the basic checkout route

404.html, fstab.yaml
Test URLs:
- After:
- https://fix-404-redirect--petplace--hlxsites.hlx.live/
- https://fix-404-redirect--petplace--hlxsites.hlx.live/?martech=off
=> Enabled folder mapping to fix react client redirect

blocks/widget-aggregator/widget-aggregator.css, templates/article-page/article-page.css, templates/insurance-page/insurance-page.css, templates/insurance-page/insurance-page.js
Commits:
- fix widget aggregator margins
- removed table of contents
- fixed grid/page layout
- added semicolon to line
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-345
Test URLs:
- After:
- https://fix-state-ins-layout--petplace--hlxsites.hlx.page/
- https://fix-state-ins-layout--petplace--hlxsites.hlx.page/?martech=off
=> fix: layout for state insurance page

templates/insurance-landing-page/insurance-landing-page.js
- function to filter out params
- function to convert array to url string
- including extra url params on button click
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-483
Test URLs:
- After:
- https://feat-utm-params-ins--petplace--hlxsites.hlx.page/
- https://feat-utm-params-ins--petplace--hlxsites.hlx.page/?martech=off
Screenshots:
=> feat: utm params for insurance landing page

react-client/src/components/design-system/card/BasicActionCard.tsx, react-client/src/routes/account/components/PaymentInformationTabContent.test.tsx, react-client/src/routes/account/components/PaymentInformationTabContent.tsx
Test URLs:
- After:
- https://83066-payment-information--petplace--hlxsites.hlx.live/
- https://83066-payment-information--petplace--hlxsites.hlx.live/?martech=off
=> 83066 payment information

.github/workflows/pre-build-ads-txt.yaml
Test URLs:
- After:
- https://ramboz-patch-1--petplace--hlxsites.hlx.live/
- https://ramboz-patch-1--petplace--hlxsites.hlx.live/?martech=off
=> fix: ads workflow conditional evaluation

templates/home-page/home-page.js
Fix #[PM-512](https://pethealthinc.atlassian.net/browse/PM-512)
Test URLs:
- After:
- https://feature-genai-homepage-addition--petplace--hlxsites.hlx.page/
- https://feature-genai-homepage-addition--petplace--hlxsites.hlx.page/?martech=off
=> PPL: Adobe GenAI - Homepage Addition

react-client/src/components/design-system/form/FormBuilder.test.tsx, react-client/src/components/design-system/form/FormBuilder.tsx, react-client/src/domain/useCases/pet/GetPetsListUseCase.test.ts
Test URLs:
- Before: https://dev--petplace--hlxsites.hlx.page/
- After:
- https://from-builder-tests--petplace--hlxsites.hlx.live/
- https://from-builder-tests--petplace--hlxsites.hlx.live/?martech=off
=> Tests for FormBuilder Component

react-client/src/components/design-system/dialog/ErrorDialog.test.tsx, react-client/src/components/design-system/dialog/ErrorDialog.tsx, react-client/src/components/design-system/dragAndDropZone/DragAndDropFileUpload.tsx, react-client/src/routes/my-pets/petId/documents/documentType/DocumentTypeIndex.tsx, react-client/src/routes/my-pets/petId/documents/documentType/components/PetDocumentsView.test.tsx, react-client/src/routes/my-pets/petId/documents/documentType/components/PetDocumentsView.tsx, react-client/src/routes/my-pets/petId/documents/documentType/useDocumentTypeIndexViewModel.tsx, react-client/src/routes/playground/playgrounds/ErrorDialogPlayground.tsx, react-client/src/routes/playground/playgrounds/index.ts
Test URLs:
- After:
- https://83735-error-message-download-api--petplace--hlxsites.hlx.live/
- https://83735-error-message-download-api--petplace--hlxsites.hlx.live/?martech=off
=> 83735 error message download api

scripts/adsense.js, styles/styles.css
- fixed some padding for side ad to thicken
- parent container changed for side ads
- removed extra indentation from styles.css
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-500
Test URLs:
- After:
- https://bugfix-article-side-ads--petplace--hlxsites.hlx.live/
- https://bugfix-article-side-ads--petplace--hlxsites.hlx.live/?martech=off
=> bugfix: side ads placement on article page

blocks/genai-search/genai-search.css, templates/gen-ai/gen-ai.js
Fix #[PM-482](https://pethealthinc.atlassian.net/browse/PM-482)
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/discovery
- After:
- https://feature-genai-insurance-cta-card--petplace--hlxsites.hlx.page/discovery
- https://feature-genai-insurance-cta-card--petplace--hlxsites.hlx.page/discovery/?martech=off
=> PPL: Adobe GenAI - Insurance Trigger Word

templates/article-page/article-page.js
Jira Ticket:
https://pethealthinc.atlassian.net/browse/PM-481
Related to: #732
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/general/pet-insurance/pet-insurance-review
- After: https://pm481-mauricio-toc--petplace--hlxsites.hlx.page/article/general/pet-insurance/pet-insurance-review
=> feat: move TOC in article after hero

blocks/genai-search/genai-search.css, scripts/adsense.js, styles/styles.css, templates/article-page/article-page.js, templates/gen-ai/gen-ai.js
Deployment Includes:
- bugfix: side ads placement on article page (#739) 
- PPL: Adobe GenAI - Insurance Trigger Word (#755) 
- feat: move TOC in article after hero (#762) 
Test URLs:
- After:
- https://sprint19-deploy--petplace--hlxsites.hlx.live/
- https://sprint19-deploy--petplace--hlxsites.hlx.live/?martech=off
=> deployment for sprint 19

blocks/header/header.css, blocks/header/header.js
https://github.com/user-attachments/assets/12572428-f0e1-4e1a-89ff-cb20f960e00a
Test URLs:
- After:
- https://83864-menubar-fix--petplace--hlxsites.hlx.live/
- https://83864-menubar-fix--petplace--hlxsites.hlx.live/?martech=off
=> Improve menu

templates/insurance-page/insurance-page.css
https://pethealthinc.atlassian.net/browse/PM-495
Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california 
- After: https://pm-495--petplace--hlxsites.hlx.page/pet-insurance/best-pet-insurance-california
=> Refactor insurance page table CSS to improve horizontal scrolling

react-client/src/components/Pet/PetWatchDrawerBody.tsx, react-client/src/components/Pet/PetWatchDrawerServiceContent.tsx, react-client/src/components/Pet/PetWatchServices.tsx, react-client/src/components/Pet/sections/PetWatchSection.tsx, react-client/src/routes/my-pets/petId/PetProfileIndex.tsx, react-client/src/routes/my-pets/petId/usePetProfileLayoutViewModel.tsx, react-client/src/routes/my-pets/petId/utils/petWatchConstants.ts, react-client/src/util/petWatchServiceUtils.ts
Test URLs:
- After:
- https://84131-improve-view-model--petplace--hlxsites.hlx.live/
- https://84131-improve-view-model--petplace--hlxsites.hlx.live/?martech=off
=> feat: improve view model bringing business rule about what should render

templates/home-page/home-page.css
https://pethealthinc.atlassian.net/browse/PM-479
Test URLs:
Before: https://main--petplace--hlxsites.hlx.page/
After:
https://pm-479--petplace--hlxsites.hlx.page/
https://pm-479--petplace--hlxsites.hlx.page/?martech=off
=> Refactor home page CSS for better responsiveness and alignment

react-client/src/components/Membership/CartDrawer.tsx, react-client/src/components/Membership/CartFooter.tsx, react-client/src/components/Membership/MembershipComparingPlanTable.tsx, react-client/src/routes/checkout/products/ProductsIndex.tsx, react-client/src/routes/checkout/products/useCheckoutProductsViewModel.tsx
https://github.com/user-attachments/assets/8c0e9f67-3d2f-43d1-83c4-249cec8f39d3
Test URLs:
- After:
- https://84252-checkout-fix-route--petplace--hlxsites.hlx.live/
- https://84252-checkout-fix-route--petplace--hlxsites.hlx.live/?martech=off
=> fix: add id from API instead of hardcoded to fix route

blocks/newsletter-signup/newsletter-signup.css, blocks/newsletter-signup/newsletter-signup.js
https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B6D092F99-6860-4093-A27F-8DDE8276531E%7D&file=newsletter.xlsx&action=default&mobileredirect=true
Test URLs:
- After:
- https://hotfix-newsletter-form-bg--petplace--hlxsites.hlx.page/
- https://hotfix-newsletter-form-bg--petplace--hlxsites.hlx.page/?martech=off
=> bugfix: background issue with css specificity

react-client/src/components/design-system/form/InputPhone.tsx, react-client/src/components/design-system/layout/Layout.test.tsx, react-client/src/components/design-system/layout/Layout.tsx, react-client/src/routes/account/AccountIndex.tsx
This PR solves the following issue:
- https://phits.visualstudio.com/PetPlace/_workitems/edit/84557/
Test URLs:
- Before: https://dev--petplace--hlxsites.hlx.page/
- After:
- https://fix-84557-phone-input--petplace--hlxsites.hlx.live/
- https://fix-84557-phone-input--petplace--hlxsites.hlx.live/?martech=off
=> fix: input phone layout

react-client/src/routes/my-pets/petId/edit/usePetEditViewModel.tsx, react-client/src/routes/my-pets/petId/form/petForm.tsx
This PR solves the following issue:
- https://phits.visualstudio.com/PetPlace/_workitems/edit/84757/
https://github.com/user-attachments/assets/71b7ce18-d9f9-4935-9ebf-b0021b1dcdf9
Test URLs:
- Before: https://dev--petplace--hlxsites.hlx.page/
- After:
- https://84757-change-on-discard--petplace--hlxsites.hlx.live/
- https://84757-change-on-discard--petplace--hlxsites.hlx.live/?martech=off
=> refactor: 84757 onDiscard behavior
